### PR TITLE
Seperate commands list

### PR DESCRIPTION
**Pull request by SpikeHD**
As the command list grows, I think it will become a bit too heavy to include in the main README, so i thought it would be a good idea to move it instead.

I also put them into a table which I thought looked a bit nicer.

### CODE REVIEW

**Comment by MlgmXyysd** [comment]
Have you all forgotten [wiki](https://github.com/Grasscutters/Grasscutter/wiki)

**Comment by SpikeHD** [comment]
I actually don't know how to send a PR for the wiki so uhhh if anyone wants to do that feel free

**Comment by lunaticwhat** [comment]
yeah that was what I ve talk about ! we should have a command list in wiki and link to it on the readme

**Comment by alt3ri** [comment]
true

**Comment by ghost** [comment]
Please make the PR to the development branch

**Pull request closed without merging**
