### PR TITLE
Remove auto creat banner on 2.7

### PR DESCRIPTION
**Pull request by longtam6**
Like tittle, your banner reset and re-creat every 5 mins but on 2.7 we just need yelan + xiao banner.

### CODE REVIEW

**Comment by KiminaNatsuki** [comment]
"+19,187 −207,016"
what the hell is this

**Comment by 4Benj** [comment]
Change target branch pls

**Comment by akbaryahya** [comment]
> Like tittle, your banner reset and re-creat every 5 mins but on 2.7 we just need yelan + xiao banner.

this is not me, i never do merge.
if you want to ask about banners, it's better to ask on discord than make something like this : |

**Comment by Birdulon** [comment]
I don't understand what you are trying to do.

**Comment by 4Benj** [comment]
Please do not make a PR from a repo that is not yours…

**Pull request closed without merging**
