### PR TITLE
Fix fields

### PR DESCRIPTION
**Pull request by ghjbvvgh**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by thecutefinder** [comment]
Where did this proto change come from?

**Comment by ghjbvvgh** [comment]
> Where did this proto change come from?

From my proto.

**Comment by KingRainbow44** [comment]
anyone test this?

**Comment by NotThorny** [comment]
Works properly, fixing the map waypoints not being unlocked correctly before.

https://user-images.githubusercontent.com/107363768/231051930-9fc2ec40-928b-4824-9a49-b3f071276f18.mp4

**Review by KingRainbow44 — APPROVED** [review]

**Pull request merged**
