### PR TITLE
Big time translation & command changes

### PR DESCRIPTION
**Pull request by supahero1**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

This PR achieves the following things:
* If failed to enter a dungeon via a command, don't send a success message (followed by a failure message),
* Updated english and polish translations to be up-to-date with everything. Redundant old properties were removed (with allowance from the maintaners, namely `shichihachi`), things like `weather`, which will be used in the nearest future, were kept.
* Along with the above, all command translations were updated in the forementioned 2 languages to include "usage" and "description" fields. Moreover, all commands are now using `commands.command_name.usage` instead of their hardcoded usage strings under the `command/commands` directory. I also beautified the Command class creation in every command file so that the line is not long as hell.
* Changed the Help command formatting to be more pleasant to the eye and hopefully more intuitive. This reflects in both `help` and `help [command]`. Additionally, `commands.help.usage` clashed with the mentioned before removal of hardcoded usage strings, so `commands.help.usage` is now `commands.help.usage_prefix` (this is the string that translates to "Usage: ").
* Additionally to the above change, `CommandMap` was fixed so that `getHandler(label)` correctly returns a command if `label` is an alias of the command (which did not work before - for some reason alias fetching was only implemented in `invoke()`).
* `HelpCommand.SendAllHelpMessage()` was quite outdated and it had a giant `if` statement that differentiated between nullish player and not nullish, even though both of the branches did the same thing. I implemented a new private function in the class - `createCommand()`, which adds one command's annotation to a `StringBuilder`, and then used that function both in `SendAllHelpMessage()` and `execute()`. `SendAllHelpMessage()`'s line length went down from 64 to 9 this way.

I would like to ask for english translation to be declared somehow as the mainstream to new or existing contributors, so that other languages can adapt the new (previously missing) fields and delete old, redundant ones, as well as adjust their translation, because, for instance, in ALL languages, `messages.dispatch.account.account_login_create_success` was translated to a FAILURE, not a SUCCESS. This was also fixed by this pr, but of course only for english and polish. Corrected romanian translation should be coming in pretty soon.

For the above translation changes, I did my research and actually was flying around the codebase to check where various props are used (in what context) so that I could adjust my translation appropriately. For this reason, I also edited one command's file so that arguments to the translation string are given in a different order to make it easier for certain languages to translate. I hope that's fine.

### CODE REVIEW

**Comment by haxxorer** [comment]
I rate it

**Comment by Birdulon** [comment]
Sorry if this comes off as a bit terse, this is my third time writing this comment as github clears the text field when I check the PR changes:

> If failed to enter a dungeon via a command, don't send a success message (followed by a failure message),

Wasn't this merged in #1459?

> I would like to ask for english translation to be declared somehow as the mainstream to new or existing contributors, so that other languages can adapt the new (previously missing) fields and delete old, redundant ones, as well as adjust their translation

That is one of the goals of #1382.

> For the above translation changes, I did my research and actually was flying around the codebase to check where various props are used (in what context) so that I could adjust my translation appropriately.

With all due respect, your time would have been better spent asking on `#development` first as there is a lot of overlap with the current and planned changes in #1382 which will likely be completed and merged this weekend. Some of your points and changes will still be relevant afterwards most of them will likely conflict.

**Comment by supahero1** [comment]
#1459 was in the same fork, don't know how it ended up being attached to this as well.

**Comment by supahero1** [comment]
regarding #1382, I don't see how it can fix other issues in my pr. To me, it seems like actual fixes are more important than some automated translation attempts. It also appears to me that specifying command usages in translations instead of hardcoding them is better too, because individual words used on the usage note can often be translated into other languages, like `<level>`. In my opinion, this pr should be merged first.

**Comment by Birdulon** [comment]
> To me, it seems like actual fixes are more important than some automated translation attempts.

No automated translation takes place in #1382, semi-automated management of the language files takes place - i.e. pre-filling untranslated keys across all languages, matching key orders to `en-US.json`, deleting keys that have been deleted from `en-US.json`, listing all keys that haven't been translated in each language, and listing missing keys.

This has been long overdue as you might imagine, and will likely be added as a Github Actions step for PRs to ensure things aren't merged with missing keys. Until then, any manual fixup is just a waste of effort, which is why some PRs were merged without full key coverage this week.

Command usage annotations being keyed in to existing usage strings is fine, but multilining all command annotations for the sake of it is a bit much, and the order doesn't even seem to be consistent. Anyway, a lot of project communication only takes place on the Discord for better or worse, so I'd really recommend getting on there before getting too invested in any large PRs.

**Comment by supahero1** [comment]
Fallbacks already exist in case other languages don't have a translation (in `Language.java`), so what's the point? This pr achieves many things, and you are trying to tell me now that a pr from 22 days ago that you guys didn't handle has precedence while it would quite literally change nothing compared to this pr. Get your priorities right. Merge this pr if you want, but if you close it, I will not try to adjust to your course of action.

**Review by KingRainbow44 — APPROVED** [review]

**Comment by supahero1** [comment]
Alright. Since you chose to accept a different pr and now this conflicts, I'm closing this, good luck on deving Grasscutter like this.

**Pull request closed without merging**
