### PR TITLE
twitter account login

### PR DESCRIPTION
**Pull request by Fauture**
## Description

twitter account login
https://www.youtube.com/watch?v=SprjlHEGw_s
**proxy https://webapi-os.account.hoyoverse.com/**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by qinastar** [comment]
这个是用twitter账号登陆吗？还是说利用接口新增了一个登录系统？

**Comment by Fauture** [comment]
> 这个是用twitter账号登陆吗？还是说利用接口新增了一个登录系统？

使用twitter接口自定义新登录验证
Customize new login authentication using twitter interface

**Comment by qinastar** [comment]
> > 这个是用twitter账号登陆吗？还是说利用接口新增了一个登录系统？
> 
> 使用twitter接口自定义新登录验证 Customize new login authentication using twitter interface

太好了，我刚好最近正在考虑账号验证系统，刚把前端写了一部分。感谢大佬！

**Comment by victor-lcr** [comment]
请问现在能在最新的编译中使用此功能吗?
Can I use this function in the latest compilation?

**Comment by memetrollsXD** [comment]
Authentication is better off just being a GC Plugin instead of being integrated into Grasscutter. You should also hash the passwords

**Pull request closed without merging**
