### PR TITLE
Major quest framework improvements

### PR DESCRIPTION
**Pull request by akatatsu27**
## Description
-Newly added ContentTriggerFire won't work because luaj can't read. Tests with tnsc4502's jnlua worked flawlessly. I have made this [branch "questing-jnlua" in my repository](https://github.com/akatatsu27/Grasscutter/tree/questing-jnlua) to illustrate the differences. Starting quest 35104 is a good way to see.
-Implement quest rewind
-QuestManager can now pass accept, fail and finish QuestTriggers to all active quests
-GameMainQuest is now responsible for handling its subQuests' conditions appropriately
-track and store in the database quest related talks in GameMainQuest (important for some conditions)
-Implement QuestGlobalVars and QuestVars
-Added various QuestTrigger handlers
-also added start() and fail()  methods to GameQuest
-fix finishCond set to null if no acceptCond
-fix if accept/fail/finish CondComb is null, getAccept/Fail/FinishCondComb returns null (should return LOGIC_NONE)
-fix some packet handlers
-fix QuestManager::addQuest() notify client only one new subQuest added (there could be multiple)
-Made more clear in the code if referring to MainQuest or SubQuest
-Added comments to some wrongly handled QuestTriggers

I suggest testing by starting quest 100301 via console command (not fully completable)

Note: for quest rewind to work properly, a slightly modified version of Birdulon's "flat.luas.scenes.full_globals.lua" is needed, which can be found here: https://github.com/akatatsu27/MoarGCResources (put ScriptSceneData in the resources folder)

## Type of changes
- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [x] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by keqingyyds** [comment]
I don't know English. Where should I put the new documents? I put it in the Resources folder. It doesn't seem to work. When you finish the task, you stay in making food, and you can't continue to complete it.

**Comment by akatatsu27** [comment]
> I don't know English. Where should I put the new documents? I put it in the Resources folder. It doesn't seem to work. When you finish the task, you stay in making food, and you can't continue to complete it.

Hello! sorry for the confusion. this PR doesn't fix the cooking. Since most questTriggers are yet to be implemented, few quests are actually completable. Also, the ScriptSceneData folder is completely unrelated with your issue. I'll update the description to be less confusing

**Review by ghost — APPROVED** [review]

**Comment by longhuan1999** [comment]
There were some issues during quest 351 in the latest version 1.2.3-dev-283a8819. I'm not sure whether it's an issue with Grasscutter or some LUA scripts?
```
21:43:46 <INFO:OpenCommandHandler> IP: 10.241.77.203 run command in console > quest @10001 add 35104
21:43:47 <INFO:LuaSerializer> {data_index=0, room_id=0, id=1005, alias=Paimon, script=Actor/Quest/Q352/Paimon, pos=Q351FirstClimb, scene_id=3}
> java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl
        at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:68)
        at emu.grasscutter.scripts.serializer.LuaSerializer.cacheType(LuaSerializer.java:191)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:139)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serializeList(LuaSerializer.java:97)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:130)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:161)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serializeMap(LuaSerializer.java:54)
        at emu.grasscutter.scripts.serializer.LuaSerializer.toMap(LuaSerializer.java:35)
        at emu.grasscutter.game.quest.GameMainQuest.addRewindPoints(GameMainQuest.java:207)
        at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:80)
        at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:181)
        at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:200)
        at emu.grasscutter.command.commands.QuestCommand.execute(QuestCommand.java:34)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:276)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:280)
        at com.github.jie65535.opencommand.OpenCommandHandler.handle(OpenCommandHandler.java:112)
        at express.Express.lambda$post$4(Express.java:131)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:65)
        ... 59 more
21:43:47 <INFO:LuaSerializer> {data_index=0, room_id=0, id=1005, alias=Paimon, script=Actor/Quest/Q352/Paimon, pos=Q351FirstQuest, scene_id=3}
> java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl
        at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:68)
        at emu.grasscutter.scripts.serializer.LuaSerializer.cacheType(LuaSerializer.java:191)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:139)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serializeList(LuaSerializer.java:97)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:130)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:161)
        at emu.grasscutter.scripts.serializer.LuaSerializer.serializeMap(LuaSerializer.java:54)
        at emu.grasscutter.scripts.serializer.LuaSerializer.toMap(LuaSerializer.java:35)
        at emu.grasscutter.game.quest.GameMainQuest.addRewindPoints(GameMainQuest.java:207)
        at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:80)
        at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:181)
        at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:200)
        at emu.grasscutter.command.commands.QuestCommand.execute(QuestCommand.java:34)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:276)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:280)
        at com.github.jie65535.opencommand.OpenCommandHandler.handle(OpenCommandHandler.java:112)
        at express.Express.lambda$post$4(Express.java:131)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3585)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:65)
        ... 59 more
21:43:47 <INFO:CommandHandler> 已添加任务 35104。
21:44:28 <ERROR:SceneScriptManager> [LUA] call trigger failed condition_EVENT_ENTER_REGION_84,emu.grasscutter.scripts.data.ScriptArgs@2bfae816
org.luaj.vm2.LuaError: script:1321 bad argument: userdata expected, got number
        at org.luaj.vm2.LuaValue.argerror(Unknown Source)
        at org.luaj.vm2.LuaValue.checkuserdata(Unknown Source)
        at org.luaj.vm2.lib.jse.JavaMethod.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:374)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:367)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:322)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$10(SceneScriptManager.java:308)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by akatatsu27** [comment]
> This is an issue (along with many others) with grasscutter, specifically the luaj library. In my testing with the jnlua library it worked as intended (addRewindPoints also needs the file I specified to work properly). Hopefully a consensus will be reached to address this issue.

**Pull request merged**
