### PR TITLE
Fix folder separation for folderNames

### PR DESCRIPTION
**Pull request by lilmayofuksu**

### CODE REVIEW

**Comment by lunaticwhat** [comment]
so true

**Comment by Melledy** [comment]
Don’t need to add a Utils::toFilePath call in your folder array since it just gets called anyways when iterating.

**Comment by lilmayofuksu** [comment]
> Don’t need to add a Utils::toFilePath call in your folder array since it just gets called anyways when iterating.

somebody forgot to edit those \\ then

**Comment by lilmayofuksu** [comment]
bruh

**Pull request closed without merging**
