### PR TITLE
[Anime Game Version update] Support 2.7

### PR DESCRIPTION
**Pull request by Konoyoru435**
## Description

Add/modify protos and code to support to Anime Game 2.7.0

## TODO

- [x] remove the obfusucated protos

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation
- [x] New version update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Yazawazi** [comment]
It worked, but some of the packet processing methods need to be changed to accommodate the update, and the obfuscated names are used in some of the proto's like mail, I'm not sure if that's correct, I need the developers involved to verify with me.

Can't display username correctly? Something strange.

**Comment by Qingbyue** [comment]
I can't log in the game with my old account.There is no problem with the new account.

**Comment by eormal** [comment]
Are you using the pre-downloaded client?

**Comment by Qingbyue** [comment]
I'm using a full 2.7 client,And I have successfully entered the game with new account.It seems to be some wrong with the database,so that I can't log in with my old account.I think the problem might be lacking some resources for Relic,I used Relic resources from 2.6 to replace the new resources.The result

 is still the same.

**Comment by Qingbyue** [comment]
Screenshot_2022-05-28-14-00-40-680_com android chrome

**Comment by Qingbyue** [comment]
Screenshot_2022-05-28-13-56-34-521_com microsoft rdc androidx

**Comment by eormal** [comment]
> Screenshot_2022-05-28-13-56-34-521_com microsoft rdc androidx
sorry I don't know how to fix this, I was trying to ask the author which client to use to run the code.

**Comment by Qingbyue** [comment]
> > 截图_2022-05-28-13-56-34-521_com microsoft rdc androidx
> > 抱歉，我不知道如何解决这个问题，我试图询问作者使用哪个客户端来运行代码。

I was really careless.I've solved this problem with old relic resources

**Comment by eormal** [comment]
> > > 截图_2022-05-28-13-56-34-521_com microsoft rdc androidx
> > > 抱歉，我不知道如何解决这个问题，我试图询问作者使用哪个客户端来运行代码。
> 
> I was really careless.I've solved this problem with old relic resources

Congratulations! Can you share the complete client for 2.7?

**Comment by Qingbyue** [comment]
> > > > 截图_2022-05-28-13-56-34-521_com microsoft rdc androidx
> > > > 抱歉，我不知道如何解决这个问题，我试图询问作者使用哪个客户端来运行代码。
> > 
> > 
> > I was really careless.I've solved this problem with old relic resources
> 
> Congratulations! Can you share the complete client for 2.7?

[2.7](https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20220429112415_dDweiEHDnBI6cKmM/GenshinImpact_2.7.0.zip)

**Comment by eormal** [comment]
> > > > > 截图_2022-05-28-13-56-34-521_com microsoft rdc androidx
> > > > > 抱歉，我不知道如何解决这个问题，我试图询问作者使用哪个客户端来运行代码。
> > > 
> > > 
> > > I was really careless.I've solved this problem with old relic resources
> > 
> > 
> > Congratulations! Can you share the complete client for 2.7?
> 
> [2.7](https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20220429112415_dDweiEHDnBI6cKmM/GenshinImpact_2.7.0.zip)

grateful! !

**Comment by luluxiaoyu** [comment]
> > > > > 截图_2022-05-28-13-56-34-521_com microsoft rdc androidx
> > > > > 抱歉，我不知道如何解决这个问题，我试图询问作者使用哪个客户端来运行代码。
> > > 
> > > 
> > > I was really careless.I've solved this problem with old relic resources
> > 
> > 
> > Congratulations! Can you share the complete client for 2.7?
> 
> [2.7](https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20220429112415_dDweiEHDnBI6cKmM/GenshinImpact_2.7.0.zip)

Isn't this client just a pre-downloaded client?

**Comment by Yazawazi** [comment]
Here is the PR, if you have questions please go to Discord to discuss.

**Review by ghost — APPROVED** [review]

**Pull request merged**
