### PR TITLE
Fix showing ban message box

### PR DESCRIPTION
**Pull request by phuchptty**
## Description
I have tested and found that, if we close the session right before sending the response packet, the client will show a "Disconnected" message instead of a ban. So I removed it.
After the client press OK or a time, the client would automatically close the session and disconnect.

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Birdulon** [comment]
The problem with leaving a banned session open is that all the handlers will still be running. A client that ignores the ban message (e.g. by running the kind of hacks that might earn them a ban in the first place) will be able to do continue playing normally.

**Comment by phuchptty** [comment]
> The problem with leaving a banned session open is that all the handlers will still be running. A client that ignores the ban message (e.g. by running the kind of hacks that might earn them a ban in the first place) will be able to do continue playing normally.

I think I can add a delay to close the session. Delay about 2 seconds then close

**Comment by GanyusLeftHorn** [comment]
I think the cleaner solution would be to introduce a new `SessionState` that disables handling of packets after being set. See `GameServerPacketHandler::handle()` for reference.

**Comment by phuchptty** [comment]
> I think the cleaner solution would be to introduce a new `SessionState` that disables handling of packets after being set. See `GameServerPacketHandler::handle()` for reference.

Yeah. That was [Birdulon](https://github.com/Birdulon) tell me in discord too

**Review by Birdulon — APPROVED** [review]

**Pull request merged**
