### PR TITLE
Added web api.

### PR DESCRIPTION
**Pull request by Someone999**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Someone999** [comment]
The missing key is a runtime-building string.

**Comment by Someone999** [comment]
## Grasscutter API



### Base Request



| ArgumentName | ArgumentType | Description                                                 | Optional |
| ------------ | ------------ | ----------------------------------------------------------- | -------- |
| Token        | string       | Token, can be set in config.json                            |          |
| Type         | string       | Request type. "command" and "player" are included currently |          |
| Data         | object       | Data of this request                                        |          |



## Request Data

### Command request

| ArgumentName | ArgumentType | Description                                                 | Optional |
| ------------ | ------------ | ----------------------------------------------------------- | -------- |
| type         | string       | Command type, "gccmd" and "commands" are included currently |          |
| data         | object       | Data of this request                                        |          |



### Command request data

  #### gccmd

| ArgumentName | ArgumentType | Description              | Optional |
| ------------ | ------------ | ------------------------ | :------: |
| command      | string       | Command to execute       |          |
| executorId   | int          | User ID of executor      |    T     |
| executorName | string       | In game name of executor |    T     |
| targetId     | int          | User ID of target        |    T     |
| targetName   | string       | In game name of target   |    T     |



#### commands

| ArgumentName | ArgumentType | Description              | Optional |
| ------------ | ------------ | ------------------------ | :------: |
| commands     | string[]     | Commands to execute      |          |
| executorId   | int          | User ID of executor      |    T     |
| executorName | string       | In game name of executor |    T     |
| targetId     | int          | User ID of target        |    T     |
| targetName   | string       | In game name of target   |    T     |



### Player request data

| ArgumentName | ArgumentType | Description                                                  | Optional |
| ------------ | ------------ | ------------------------------------------------------------ | :------: |
| attr         | string       | The attribute to operate.                                    |          |
| playerId     | int          | Player user ID                                               |    T     |
| playerName   | string       | Player name                                                  |    T     |
| op           | string       | Operation to do on attribute. Contained ["get", "set", "add", "setHelp", "addHelp"] currently. |          |
| data         | object       | Data of specified command                                    |          |



### pos.set and pos.add

| ArgumentName | ArgumentType  | Description                                                  | Optional |
| ------------ | ------------- | ------------------------------------------------------------ | :------: |
| x            | float\|string | x coordinate. All strings will be replaced as the x of the player currently has. |    T     |
| y            | float\|string | y coordinate. All strings will be replaced as the y of the player currently has. |    T     |
| z            | float\|string | z coordinate. All strings will be replaced as the z of the player currently has. |    T     |
| sceneId      | int\|string   | Scece ID. All strings will be replaced as the scene ID of the player currently has. |    T     |

### godMode.set

| ArgumentName | ArgumentType | Description             | Optional |
| ------------ | ------------ | ----------------------- | :------: |
| enabled      | bool         | Turn on god mode or not |    T     |

**Comment by Birdulon** [comment]
This sort of functionality is better implemented as a plugin, it's been brought up before https://github.com/Grasscutters/Grasscutter/pull/1433

**Comment by Someone999** [comment]
my plugin can not run on gc because it can not load any dependency module if run as a plugin.

**Comment by Someone999** [comment]
i'm confused.

**Pull request closed without merging**
