### PR TITLE
Fix game data lost

### PR DESCRIPTION
**Pull request by zhaodice**
## Description

Fix data lost when other device logins the same account.
Force to make account offline , which logins already.

## Issues fixed by this PR

#1162

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by zhaodice** [comment]
#1188 resolved

**Comment by ghost** [comment]
You dont need this PR as players are supposed to be auto disconnected if they [log in again from a different client](https://github.com/Grasscutters/Grasscutter/blob/e6fa00e55d7cd61d20bc67d8faa9c0fbfb64fbbd/src/main/java/emu/grasscutter/game/player/Player.java#L1216).

**Comment by zhaodice** [comment]
> You dont need this PR as players are supposed to be auto disconnected if they [log in again from a different client](https://github.com/Grasscutters/Grasscutter/blob/e6fa00e55d7cd61d20bc67d8faa9c0fbfb64fbbd/src/main/java/emu/grasscutter/game/player/Player.java#L1216).

No,I have tested. disconnection doesn't always work .

example there is a account:
1.login from client A 
2.login from client B (A was disconnected)
3.login from client A again (B was NOT disconnected)
4.A and B can play simultaneously!

**Comment by zhaodice** [comment]
disconnection may works once, but it will be unavailable anymore

**Comment by zhaodice** [comment]
although A and B can play simultaneously, only one what they have done can be saved.

**Comment by zhaodice** [comment]
I know where is your bug, I will refine my code depends on your implement

**Pull request closed without merging**
