### PR TITLE
feature(support 2.8): upgrade grasscutter to 2.8

### PR DESCRIPTION
**Pull request by Konoyoru435**
## Description

***The patch is still under discussion and this pr may be replaced by backroom at any time***

Support Anime Game 2.8.

1. Upload new protos, and I added proto for almost all activities to help developers implement more activities. To solve the memory issues, add `gradle.properties`;
2. Fix some bugs cuz by new protos, a painful experience that includes a lot of guesswork;
3. Modified the login logic, from now on if you want to use the grasscutter for this branch you have to patch your `UserAssembly.dll`, but keep the seed exchange logic.

Because of the obfuscation, a large number of proto field names have been changed, and change to the original de-obfuscated logic and fields is unavoidable, so I can only rely on my personal guesses and related logical to fix them. I apologize if the functionality is broken.

BREAKING CHANGE: ALL

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation
- [x] New Version

## TODO List

- [ ] Remove useless proto;
- [ ] Provide comments for obfuscated fields.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by GanyusLeftHorn** [comment]
🙀

**Comment by lhhxxxxx** [comment]
🙀

**Comment by NctimeAza** [comment]
OMG

**Comment by alt3ri** [comment]
real

**Comment by ChisatoNishikigi73** [comment]
omg

**Comment by Jelen0126** [comment]
OMGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

**Comment by 2y8e9h22** [comment]
ＯＫ(ゝω・´★)

**Comment by Koko-boya** [comment]
🙀

**Comment by nikoflora** [comment]
OMG!!!!!!!

**Comment by Yazawazi** [comment]
This PR is closed because Backroom has provided a new implementation that will submit a PR in 24 hours.

If you are using a UA patch that only keeps the seed exchange logic, try using this branch: https://github.com/WaziDuck/herbicide

**Pull request closed without merging**
