### PR TITLE
Skill particle generation

### PR DESCRIPTION
**Pull request by Logictc**
## Description

A not entirely complete implement of skill particle generation.
ToDo: need to address difference between press and hold. (treat as short for now)
Issue: some characters are able to double trigger generation (Ayato, Keqin)

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by 4Benj** [comment]
Why was #1059 closed and this opened?

**Comment by Logictc** [comment]
> 

Yes, I was told to use tab for all indentation so I closed the previous one.

**Review by ghost — APPROVED** [review]
You can find how many orbs are generated from skills in BinOutput. It could be a little difficult to parse though, so I will approve this for now.

**Comment by Logictc** [comment]
> You can find how many orbs are generated from skills in BinOutput. It could be a little difficult to parse though, so I will approve this for now.

Yeah, looking at that gives me very good insight on how to properly implement this, it seems the calculation is done with combining how many times client trigger generation call and how many to generate per call defined in the BinOutput. I will try to improve this with BinOutput. Thanks.

**Pull request merged**
