### PR TITLE
Character fetter system

### PR DESCRIPTION
**Pull request by Konoyoru435**
I'm working on the character fetter system and have gotten the character fetter working (returning levels, experience, all stories and voices).

Here is the list of work that needs to be done:

<del>To reach a certain degree of fetter level to unlock the relevant voice and story. (Extract judgment information from `OpenCond` (a little complicated, with multiple judgments). (I tried to use a for loop, but I wrote four levels, GG))</del>

- [x] When the fetter level of a character reaches 10, the player will be given the name card corresponding to that character;
    - [x] Need to parse `RewardExcelConfigData.json`;
    - [x] Know the response from server;
    - [x] Go to sleep first.
- [x] Add the command to modify the character's fetter level.

### CODE REVIEW

**Comment by Yazawazi** [comment]
Command:
- Use: `/setfetterlevel [level (0-10)]`
- Sets your fetter level for your current active character.

**Comment by Yazawazi** [comment]
This PR is on hold for a while, because I'm studying the data returned by the server after the character's fetter level reaches 10.
But the highest level of fetter level of my account character is only 7, so I first plan to play the official server to improve the level of fetter level of the character.

**Comment by Yazawazi** [comment]
After sending a name card, I found a problem: the reward pickup prompt on the client disappears, but when I open the character interface again, the reward pickup prompt on the client still exists. Does anyone know what this is about? Or do I forget to deal with some packets?

**Comment by Yazawazi** [comment]
Got it! No packet, just `.addRewardedFetterLevelList`!

**Comment by Yazawazi** [comment]
Local test passed! Woohoo!

**Comment by alt3ri** [comment]
Congrats!

**Review by alt3ri — APPROVED** [review]

**Review by memetrollsXD — APPROVED** [review]
Everything looks handled

**Comment by Yazawazi** [comment]
I'm sorry, I forgot that my PR wasn't closed and then uploaded my other commit (tp improved).

**Review by ghost — APPROVED** [review]

**Pull request merged**
