### PR TITLE
Add QuestEncryptionKeys.json

### PR DESCRIPTION
**Pull request by TotallyNotOndre**
## Description
#1561 forgot to add [QuestEncryptionKeys.json](https://gist.github.com/Hartie95/8b035f144fa17d5c43d17665ee460ba7#file-questencryptionkeys-json) into a data folder so i leave it here

## Issues fixed by this PR
- Fixes `<ERROR:emu.grasscutter.data.ResourceLoader> Unable to load quest keys.`
Before fix:
Before
After fix:
After

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by ghost** [comment]
Cutscene encryption keys should be put in the `resources` folder since they are extracted from the client. (Yes, i know theyre currently loaded from the `data` folder)

**Comment by Hartie95** [comment]
It should also not break anything if the file is not there. The file is also only needed for 2.7+ prerendered cutscene support.

**Comment by Hartie95** [comment]
> Cutscene encryption keys should be put in the `resources` folder since they are extracted from the client. (Yes, i know theyre currently loaded from the `data` folder)

They are not really extracted from the client, for 2.7+ they aren't included in the client and get only send by the server as far as I know.

**Comment by ghost** [comment]
> They are not really extracted from the client, for 2.7+ they aren't included in the client and get only send by the server as far as I know.

That is true, I still think they blong more in resources than data though.

**Pull request closed without merging**
