### PR TITLE
Upgrade to versions of Java beyond 8

### PR DESCRIPTION
**Pull request by KingRainbow44**
**This update requires the use of JRE/JDK 11+.**
Completes task: #57

Included is:
- An upgrade to Morphia 2.x
- A keystore update (the existing one doesn't like newer versions of Java)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by fumbling644o** [comment]
> A keystore update

...I don't see this?

**Comment by MlgmXyysd** [comment]
I think we can implement https://github.com/Grasscutters/Grasscutter/pull/108 again

**Comment by fumbling644o** [comment]
@MlgmXyysd #125 does the same thing, just without the fancy shorthand constructors from a newer version of Java.

But, we could, if we wanted to make the code slightly less unsightly.

**Comment by MlgmXyysd** [comment]
> @MlgmXyysd #125 does the same thing, just without the fancy shorthand constructors from a newer version of Java.
> 
> But, we could, if we wanted to make the code slightly less unsightly.

Yes, I mean to change to new constructors

**Pull request merged**
