### PR TITLE
Implement npc shop

### PR DESCRIPTION
**Pull request by Kengxxiao**
~~I finally separated these parts to 3 single one 🦀~~ 

This part implemented npc shop feature.
    - Primogem, Mora, Genesis Crystal and custom items cost are supported.
    - Shop Limit feature is available.

Here is a preview

image

### CODE REVIEW

**Comment by 4Benj** [comment]
Talking to Blanche (General Store) in Mondstadt seems to work

**Review by 4Benj — APPROVED** [review]

**Comment by 4Benj** [comment]
However, maybe in shop.json it can be structured like so
```
[
	{
		"shopId": 1004,
		"items": [
			{
				"goodsId": 1004202,
				"goodsItem": {
					"Id": 202,
					"Count": 1000000
				},
				"scoin": 1,
				"buyLimit": 500,
				"beginTime": 1575129600,
				"endTime": 2051193600,
				"minLevel": 1,
				"maxLevel": 99
			},
			{
				"goodsId": 10048006,
				"goodsItem": {
					"Id": 108006,
					"Count": 20
				},
				"scoin": 1,
				"buyLimit": 50000,
				"beginTime": 1575129600,
				"endTime": 2051193600,
				"minLevel": 1,
				"maxLevel": 99
			},
			{
				"goodsId": 10048033,
				"goodsItem": {
					"Id": 108033,
					"Count": 20
				},
				"scoin": 1,
				"buyLimit": 50000,
				"beginTime": 1575129600,
				"endTime": 2051193600,
				"minLevel": 1,
				"maxLevel": 99
			}
		]
	}
]
```

**Comment by Kengxxiao** [comment]
> However, maybe in shop.json it can be structured like so
> 
> ```
> [
> 	{
> 		"shopId": 1004,
> 		"items": [
> 			{
> 				"goodsId": 1004202,
> 				"goodsItem": {
> 					"Id": 202,
> 					"Count": 1000000
> 				},
> 				"scoin": 1,
> 				"buyLimit": 500,
> 				"beginTime": 1575129600,
> 				"endTime": 2051193600,
> 				"minLevel": 1,
> 				"maxLevel": 99
> 			},
> 			{
> 				"goodsId": 10048006,
> 				"goodsItem": {
> 					"Id": 108006,
> 					"Count": 20
> 				},
> 				"scoin": 1,
> 				"buyLimit": 50000,
> 				"beginTime": 1575129600,
> 				"endTime": 2051193600,
> 				"minLevel": 1,
> 				"maxLevel": 99
> 			},
> 			{
> 				"goodsId": 10048033,
> 				"goodsItem": {
> 					"Id": 108033,
> 					"Count": 20
> 				},
> 				"scoin": 1,
> 				"buyLimit": 50000,
> 				"beginTime": 1575129600,
> 				"endTime": 2051193600,
> 				"minLevel": 1,
> 				"maxLevel": 99
> 			}
> 		]
> 	}
> ]
> ```

Thanks for your reply~
Now its structure has been modified to this type and more consumable items samples are provided

**Review by memetrollsXD — APPROVED** [review]
Tested and worked

**Pull request merged**
