### PR TITLE
Create installer script for Debian/Ubuntu

### PR DESCRIPTION
**Pull request by TurtleIdiot**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

This PR is an installer script for Debian/Ubuntu linux

What the script does (in order):
- Installs dependencies the script needs to fetch and set up grasscutter (curl, wget, openssl, unzip, git)
- Installs dependencies for grasscutter (mongodb, openjdk-17-jre)
- Fetches latest stable action build using nightly link
- Fetches data and keys from main repo using a sparse/partial checkout
- Runs `-handbook` to generate handbook and `config.json`
- Replaces `127.0.0.1` in config.json with IP obtained from user prompt
- Generates self-signed CA and SSL certificates and keystore.p12 (see below)
- Cleans up temporary files

Why a custom keystore.p12 is generated:
When I was manually installing gc on my linux server, the title screen door animation would play and then say "Connection timed out"
This is because the default keystore.p12 is generated for localhost only.
The script generates a keystore.p12 with the correct IP address

Running:
```
mkdir gc-autoinstall
cd gc-autoinstall
wget https://github.com/TurtleIdiot/Grasscutter/raw/development/install.sh
chmod +x ./install.sh
sudo ./install.sh
```

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by TurtleIdiot** [comment]
I'll upload a video of the install process tomorrow

**Comment by mingjun97** [comment]
Could the usage be something like `sh -c "$(curl -fsSL https://github.com/TurtleIdiot/Grasscutter/raw/development/install.sh)"`?

**Comment by TurtleIdiot** [comment]
As long as the script is executed as sudo, it should work

**Review by ghost — APPROVED** [review]

**Comment by YorhaX2P** [comment]
> As long as the script is executed as sudo, it should work

I got error when I tried to install `sudo ./install.sh`

**Please select the branch you wish to install**
2) development

**Do you wish to proceed and install grasscutter?**
1) Yes

Updating package cache...
Installing setup dependencies...
Done
Installing grasscutter dependencies...
**E: Package 'mongodb' has no installation candidate**

What I can do?

**Comment by TurtleIdiot** [comment]
> **E: Package 'mongodb' has no installation candidate**

What distro are you on?

**Comment by YorhaX2P** [comment]
> 

I am on Ubuntu 22.04.3 LTS
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Pull request merged**
