### PR TITLE
authentication system

### PR DESCRIPTION
**Pull request by exzork**
login : dispatchserver/grasscutter/login
register: dispatchserver/grasscutter/register

You get JWT token, payload are token, username, and uid.
and copy token to username field when logging in

### CODE REVIEW

**Comment by exzork** [comment]
ah forgot to add the payload
login : {"username":".....","password":"....."}
register: {"username":"...","password":"...","password_confirmation":"...","email":"..."}

**Comment by 4Benj** [comment]
can someone  add me as a reviewer on this so I can go over this later? I was actually going to work on this after I finished the mail system and I have quite a bit of experience developing authentication systems

**Comment by exzork** [comment]
> can someone add me as a reviewer on this so I can go over this later? I was actually going to work on this after I finished the mail system and I have quite a bit of experience developing authentication systems

i'm happy that you have experience in it

**Comment by MlgmXyysd** [comment]
After completion, I may implement the client (maybe when I'm free, because I'm going back to school tomorrow), so I add myself as a reviewer

**Comment by 4Benj** [comment]
> > can someone add me as a reviewer on this so I can go over this later? I was actually going to work on this after I finished the mail system and I have quite a bit of experience developing authentication systems
> 
> i'm happy that you have experience in it

I have quickly glanced over it and what you have now is a great start. However I won’t leave my final review until it’s further along.

Changes I suggest
1. adding JWT instead of sending the raw single sign in token with the username and uid within it (the signing token should be a random string saved to the config upon first launch)
2. The single sign in shouldn’t be a database entry, you can setup a hash map inside the dispatch server with the token as the key and something identifying as the value.
3. Consider adding a authentication mode in the config, there maybe multiple in the future and leave support for the option we have now. Especially for testing and development we want to be able to login with just a username.

**Comment by exzork** [comment]
> > > can someone add me as a reviewer on this so I can go over this later? I was actually going to work on this after I finished the mail system and I have quite a bit of experience developing authentication systems
> > 
> > 
> > i'm happy that you have experience in it
> 
> I have quickly glanced over it and what you have now is a great start. However I won’t leave my final review until it’s further along.
> 
> Changes I suggest
> 
> 1. adding JWT instead of sending the raw single sign in token with the username and uid within it (the signing token should be a random string saved to the config upon first launch)
> 2. The single sign in shouldn’t be a database entry, you can setup a hash map inside the dispatch server with the token as the key and something identifying as the value.
> 3. Consider adding a authentication mode in the config, there maybe multiple in the future and leave support for the option we have now. Especially for testing and development we want to be able to login with just a username.

Thanks for your opinion, I'll change it later.

**Comment by exzork** [comment]
image
Can't use JWT as username because of maximal length of the field is 50

**Comment by 4Benj** [comment]
> image
> Can't use JWT as username because of maximal length of the field is 50

The current plan is for the authentication system to be used by an external service or webpage like glass cutter-x. Which will then copy read the token from JWT to the user’s clipboard so it can later be used in game.

056C6731-0A50-4023-A363-08706B09AC0D

**Comment by exzork** [comment]
> > image
> > Can't use JWT as username because of maximal length of the field is 50
> 
> The current plan is for the authentication system to be used by an external service or webpage like glass cutter-x. Which will then copy read the token from JWT to the user’s clipboard so it can later be used in game.
> 
> 056C6731-0A50-4023-A363-08706B09AC0D
So the jwt token will be used to get the real token right? Adding one more endpoint

**Comment by 4Benj** [comment]
> So the jwt token will be used to get the real token right? Adding one more endpoint

Yes, why is another endpoint needed?

**Comment by exzork** [comment]
> > So the jwt token will be used to get the real token right? Adding one more endpoint
> 
> Yes, why is another endpoint needed?

Because we can't unpack jwt token on the launcher right? Or we will use the payload of the jwt as token ?

**Comment by 4Benj** [comment]
> > > So the jwt token will be used to get the real token right? Adding one more endpoint
> > 
> > 
> > Yes, why is another endpoint needed?
> 
> Because we can't unpack jwt token on the launcher right? Or we will use the payload of the jwt as token ?

We can actually, we just can’t verify the token. However, that isn’t important since it isn’t the final stage of authentication and we don’t have anything we can modify related to the account

**Comment by exzork** [comment]
> > > > So the jwt token will be used to get the real token right? Adding one more endpoint
> > > 
> > > 
> > > Yes, why is another endpoint needed?
> > 
> > 
> > Because we can't unpack jwt token on the launcher right? Or we will use the payload of the jwt as token ?
> 
> We can actually, we just can’t verify the token. However, that isn’t important since it isn’t the final stage of authentication and we don’t have anything we can modify related to the account

Okay, done with that. payload are token, username and uid. Can you check that?

**Comment by 4Benj** [comment]
> > > > > So the jwt token will be used to get the real token right? Adding one more endpoint
> > > > 
> > > > 
> > > > Yes, why is another endpoint needed?
> > > 
> > > 
> > > Because we can't unpack jwt token on the launcher right? Or we will use the payload of the jwt as token ?
> > 
> > 
> > We can actually, we just can’t verify the token. However, that isn’t important since it isn’t the final stage of authentication and we don’t have anything we can modify related to the account
> 
> Okay, done with that. payload are token, username and uid. Can you check that?

Everything looks good. I can’t test it right now but once I do I will submit my review and I may send a small changes PR to your repository as well later for a bit of polish.

**Comment by exzork** [comment]
> > > > > > So the jwt token will be used to get the real token right? Adding one more endpoint
> > > > > 
> > > > > 
> > > > > Yes, why is another endpoint needed?
> > > > 
> > > > 
> > > > Because we can't unpack jwt token on the launcher right? Or we will use the payload of the jwt as token ?
> > > 
> > > 
> > > We can actually, we just can’t verify the token. However, that isn’t important since it isn’t the final stage of authentication and we don’t have anything we can modify related to the account
> > 
> > 
> > Okay, done with that. payload are token, username and uid. Can you check that?
> 
> Everything looks good. I can’t test it right now but once I do I will submit my review and I may send a small changes PR to your repository as well later for a bit of polish.

Great! will mark this as ready for review

**Comment by 4Benj** [comment]
> Great! will mark this as ready for review

Just an FYI for anyone who is going to use this before it gets accepted, my small changes may change some of the responses from the routes slightly.

**Comment by MlgmXyysd** [comment]
Nice job.  I took a cursory look, there are some questions:
1. How can we provide certificates to users with `UseSSL=true`?  Or have to set `UseSSL=false` and use a reverse proxy service (like Nginx) with HTTPS enabled?
2. How can the user revoke the token to log out of both the JWT and the game?  How to change the password?
3. How do we modify the hash algorithm for access to possible third-party account systems (such as forums)?

**Comment by exzork** [comment]
> Nice job. I took a cursory look, there are some questions:
> 
> 1. How can we provide certificates to users with `UseSSL=true`?  Or have to set `UseSSL=false` and use a reverse proxy service (like Nginx) with HTTPS enabled?
> 2. How can the user revoke the token to log out of both the JWT and the game?  How to change the password?
> 3. How do we modify the hash algorithm for access to possible third-party account systems (such as forums)?

1. For certificate i'll prefer to use the second one, that is use reverse proxy to provide ssl. But it would be the problem for those who don't have domain on their vps. So maybe for that case useSSL=true can't be used. Service like nginx can override SSL from dispatchserver even though that already have SSL (lemme check that later ).
2. For game token ( the one that is in jwt payload ) are one time use only. Currently after user use it, it's gone, or it's better to keep that token until user logged out? if so i'll add logout endpoint. For changing password i'll add another endpoint. And in case of forgotten password i have an idea to add command that change the user password so they can change it again.
3. If needed i'll change the hash algorithm to BCrypt, or do you mean that we can change the algorithm through config file?

**Comment by exzork** [comment]
Well, nginx can do that
image
image

**Comment by 4Benj** [comment]
Hey! I've made a [PR](https://github.com/exzork/Grasscutter/pull/2) to your repository with my changes. Most of the changes I was going to make originally was actually done in a later commit (such as 3d06ecb).
The changes I've made is listened in the [PR](https://github.com/exzork/Grasscutter/pull/2).
Sorry for taking so long to do this, I wasn't expecting the mail system to be such a headache lol.

**Comment by exzork** [comment]
> Hey! I've made a [PR](https://github.com/exzork/Grasscutter/pull/2) to your repository with my changes. Most of the changes I was going to make originally was actually done in a later commit (such as [3d06ecb](https://github.com/Grasscutters/Grasscutter/commit/3d06ecbd5bab8e5d688267ff0a832c1cbb79718a)). The changes I've made is listened in the [PR](https://github.com/exzork/Grasscutter/pull/2). Sorry for taking so long to do this, I wasn't expecting the mail system to be such a headache lol.

All looks good, except that one dispatch server line formating 🤣. Gonna merge that on my fork

**Review by 4Benj — APPROVED** [review]

**Comment by MlgmXyysd** [comment]
> 1. For certificate i'll prefer to use the second one, that is use reverse proxy to provide ssl. But it would be the problem for those who don't have domain on their vps. So maybe for that case useSSL=true can't be used. Service like nginx can override SSL from dispatchserver even though that already have SSL (lemme check that later ).

If we have to use reverse proxy, I think we can directly delete `UseSSL` and SSL keys.

> 3. If needed i'll change the hash algorithm to BCrypt, or do you mean that we can change the algorithm through config file?

Yes. I mean the config file.

**Comment by exzork** [comment]
>If we have to use reverse proxy, I think we can directly delete UseSSL and SSL keys.

That's where things got complicated, personally i wouldn't delete useSSL and SSL keys because not all of gc server will enable UseAuth and/or running behind reverse proxy.

>Yes. I mean the config file.

Oh okay, probably tomorrow i'll be trying to add two another common hash ( BCrypt and SCrypt, and maybe PBKDF2 )

**Comment by exzork** [comment]
https://github.com/exzork/GCAuth
Plugin implementation for this PR, and i will be closing this. If any change needed for auth-system feel free to PR on my repo.

**Pull request closed without merging**
