### PR TITLE
Add git short rev to version

### PR DESCRIPTION
**Pull request by RealHeart**
## Description

Add git short rev to version

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by mingjun97** [comment]
I think this duplicate with PR #797?

**Comment by RealHeart** [comment]
> I think this duplicate with PR #797?

How about now

**Comment by mingjun97** [comment]
TBH, I'm not good at making a proper build script, feel free to improve this part. 

No intention to blame you, I personally don't like put the git hash into the version too much. Because currently the build script will build jar with name like `grasscutter-1.1.2-dev.jar`. If put git hash in the version. We may have some mess, e.g. have to manually delete old jar file after commit.

**Comment by RealHeart** [comment]
> TBH, I'm not good at making a proper build script, feel free to improve this part.
> 
> No intention to blame you, I personally don't like put the git hash into the version too much. Because currently the build script will build jar with name like `grasscutter-1.1.2-dev.jar`. If put git hash in the version. We may have some mess, e.g. have to manually delete old jar file after commit.

I think adding a hash after the version is helpful for users to identify.

**Comment by Birdulon** [comment]
Should be obsoleted by d4bb7c9

**Pull request closed without merging**
