### PR TITLE
Fix crash and revise route

### PR DESCRIPTION
**Pull request by mingjun97**
* Fix another point which will trigger iOS client to crash when login
* Revise `compareProtocolVersion` route to handle all method

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by mingjun97** [comment]
Still got crashed. Give me some time to figure it out. 🤣 Sorry for bothering. TBH, I don't have built environment locally so I rely on the github action builds..

**Comment by 4Benj** [comment]
> Still got crashed. Give me some time to figure it out. 🤣 Sorry for bothering. TBH, I don't have built environment locally so I rely on the github action builds..

Does the JDK not work on m1 macs or something?

**Comment by mingjun97** [comment]
> > Still got crashed. Give me some time to figure it out. 🤣 Sorry for bothering. TBH, I don't have built environment locally so I rely on the github action builds..
> 
> Does the JDK not work on m1 macs or something?

I'm not a Java guy so I was kind of lazy to setup the environment.

**Comment by 4Benj** [comment]
> > > Still got crashed. Give me some time to figure it out. 🤣 Sorry for bothering. TBH, I don't have built environment locally so I rely on the github action builds..
> > 
> > 
> > Does the JDK not work on m1 macs or something?
> 
> I'm not a Java guy so I was kind of lazy to setup the environment.

You should be able to see all requests if you set debug mode to “ALL” which provides a lot more detail and should help you a lot if you are still having issues

**Comment by mingjun97** [comment]
> > > > Still got crashed. Give me some time to figure it out. 🤣 Sorry for bothering. TBH, I don't have built environment locally so I rely on the github action builds..
> > > 
> > > 
> > > Does the JDK not work on m1 macs or something?
> > 
> > 
> > I'm not a Java guy so I was kind of lazy to setup the environment.
> 
> You should be able to see all requests if you set debug mode to “ALL” which provides a lot more detail and should help you a lot if you are still having issues

Made it works! Thank you! I patched only one if-branch for user not found. Now the patch is on both if-branches and shold works perfectly.

**Comment by 4Benj** [comment]
Hold on, I have a potential fix that might end up fixing this without needing to change the routes

**Comment by mingjun97** [comment]
Just downloaded the server jar and tested roughly. Should be ready to merge. 

Feel free to push to this PR or merge it then revert somehow. :)

**Pull request merged**
