### PR TITLE
Sorted commands

### PR DESCRIPTION
**Pull request by dianwangwin**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes
Sorted commands and modified help commands

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by Birdulon — COMMENTED** [review]
Sorting the commands into `player` and `server` folders while categorizing them into `SCENE`/`ITEMS`/`PLAYER`/`MISC`/`PERMISSIONS` seems like a strange choice.

**Comment by dianwangwin** [comment]
So how would you suggest categorizing them?

**Comment by dianwangwin** [comment]
> Sorting the commands into `player` and `server` folders while categorizing them into `SCENE`/`ITEMS`/`PLAYER`/`MISC`/`PERMISSIONS` seems like a strange choice.

Personally I actually think commands need to be categorized a little bit now so I did that

**Comment by KingRainbow44** [comment]
I will be closing this PR due to both **inactivity** and the **merge conflicts** that have incurred. 
If you want to resolve the merge conflicts, feel free to reopen this PR.

**Pull request closed without merging**
