### PR TITLE
Use the old version of the drop system.

### PR DESCRIPTION
**Pull request by ERthereal**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Issues fixed by this PR
In the new version of Grasscutter, monsters do not drop any items

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] My pull request is unique and no other pull requests have been opened for these changes
- [X] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [X] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Hartie95** [comment]
This looks kinda like a workaround, instead of addressing the problem. 
Did you make sure your resources are up to date? Did you debug by chance why the fallback to the old drop system doesn't happen?

**Comment by Hartie95** [comment]
Oh, do you by chance have scripts disabled for big world in the config? This would cause not meta object to exist, and thus not create drops.
But in that's case, you should check if meta == null || !handleDropMonster

**Comment by scooterboo** [comment]
Using /troubleshoot can figure this stuff out pretty quickly.

**Comment by ERthereal** [comment]
> 这看起来有点像解决方法，而不是解决问题。您是否确保您的资源是最新的？您是否偶然调试了为什么不会回退到旧的丢弃系统？

I confirm that my resources are up-to-date. When I start Grasscutter with debug mode, I found that if the JSON related to dropping does not exist in the resources, Grasscutter can still load the JSON in the resources successfully. This should mean that Grasscutter will never return to the old version of the drop system.

**Comment by ERthereal** [comment]
> 哦，您是否偶然在配置中为大世界禁用了脚本？这将导致元对象不存在，因此不会创建丢弃。但在这种情况下，您应该检查 meta == 空 ||！handleDropMonster

It seems unrelated to whether ScriptInBigWorld is enabled or not.

**Pull request closed without merging**
