### PR TITLE
Add config option to change console server's signature, namecard, level and world level

### PR DESCRIPTION
**Pull request by Arikatsu**
the changes here adds a config option which allows to be able to change Server's signature.

### CODE REVIEW

**Comment by lunaticwhat** [comment]
nice one ! should be better if including every remaining hardcoded values like `Level`, `WorldLevel`, `NameCardId`

**Comment by lunaticwhat** [comment]
my suggest 

( idk how to make a change suggest for real )

**Comment by Arikatsu** [comment]
alright imma do it right now

**Comment by Arikatsu** [comment]
did it

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
You dont need to put it in game constants if you already have the values in the config. Its not a big deal though, i will fix it later if someone else does it.

**Pull request merged**
