### PR TITLE
replace luaj with jnlua

### PR DESCRIPTION
**Pull request by akatatsu27**
## Description
This PR is based on [tnsc4502](https://github.com/tnsc4502)'s PR
jnlua is 2-4 times faster and uses half, or even less, memory than luaj. It also has significantly less (if any) issues processing lua scripts.
jnlua fixes and/or enables us to enhance many outstanding issues regarding: scripts (duh), quests, sceneGroup loading, and general progression.

 However, because jnlua uses the java native library (JNI), it requires a separate library for each combination of OS and architecture. this PR has compiled native libraries for:
-amd64/x86_64 windows
-i686/x86 windows
-amd64/x86_64 linux
-i686/x86 linux
-amd64 mac
-aarch64 mac (special thanks to [klakpin](https://github.com/klakpin) for compiling and testing!)

While the above cover well above 99% of use cases, I'm planning (trying) to add the binary for 32bit mac, however, contributions and suggestions for systems are welcome (all required files for compiling the native library can be found here: https://github.com/akatatsu27/JNLua_GC/tree/master/native)
The description will be updated when more systems are supported.
## Issues fixed by this PR
#1703 
#1725 

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by 2y8e9h22** [comment]
I hope that the binary files of arm64

**Comment by pfyy** [comment]
thank god luaj is finally deprecated
luaj never will implement ScriptLib

**Comment by Birdulon** [comment]
> thank god luaj is finally deprecated

GC won't be merging any JNI.

**Comment by pfyy** [comment]
> > thank god luaj is finally deprecated
> 
> GC won't be merging any JNI.

pity
if you consider it more important than correctness

**Comment by Bannyfelt13** [comment]
> > > thank god luaj is finally deprecated
> > 
> > 
> > GC won't be merging any JNI.
> 
> pity if you consider it more important than correctness

For grasscutter, all it needs is stability

**Comment by pfyy** [comment]
> > > > thank god luaj is finally deprecated
> > > 
> > > 
> > > GC won't be merging any JNI.
> > 
> > 
> > pity if you consider it more important than correctness
> 
> For grasscutter, all it needs is stability

you are so easily satisfied
GC is still full of unfixed problems and unimplemented features
abyss, serenitea pot, quest, world script...

**Comment by Bannyfelt13** [comment]
> 


Unfortunately, for Grasscutter, it should implement rather than simply replace an engine

**Comment by Bannyfelt13** [comment]
> > > > > thank god luaj is finally deprecated
> > > > 
> > > > 
> > > > GC won't be merging any JNI.
> > > 
> > > 
> > > pity if you consider it more important than correctness
> > 
> > 
> > For grasscutter, all it needs is stability
> 
> you are so easily satisfied GC is still full of unfixed problems and unimplemented features abyss, serenitea pot, quest, world script...


Unfortunately, for Grasscutter, it should implement rather than simply replace an engine

**Comment by pfyy** [comment]
> > > > > > thank god luaj is finally deprecated
> > > > > 
> > > > > 
> > > > > GC won't be merging any JNI.
> > > > 
> > > > 
> > > > pity if you consider it more important than correctness
> > > 
> > > 
> > > For grasscutter, all it needs is stability
> > 
> > 
> > you are so easily satisfied GC is still full of unfixed problems and unimplemented features abyss, serenitea pot, quest, world script...
> 
> Unfortunately, for Grasscutter, it should implement rather than simply replace an engine

**luaj never will implement ScriptLib correctly**
luaj was a mistake from the beginning
it is meant to be replaced

**Comment by akatatsu27** [comment]
> > thank god luaj is finally deprecated
> 
> GC won't be merging any JNI.

sun's jdk itself supports linux, windows and macos. in older versions it supported solaris (unmaintaines unix derivative), and in the case of openjdk, some versions support suse SLES (enterprise server based on linux), and IBM AIX (UNIX derivative marketed for workstations and enterprise servers). Given that mongodb supports only linux, x86_64 windows, and mac, I think we have no reason to seek to actively support other platforms. 
Anyone smart and stubborn enough to setup java and mongodb on their custom os written in brainfuck for a mips SoC, would have absolutely zero trouble compiling one more library. Additionally, since I made this PR, it would be my responsibility to troubleshoot and assist with jnlua issues. 
Core gameplay development has stagnated for months, and we need a solution

**Comment by HKunogi** [comment]
> > > thank god luaj is finally deprecated
> > 
> > 
> > GC won't be merging any JNI.
> 
> sun's jdk itself supports linux, windows and macos. in older versions it supported solaris (unmaintaines unix derivative), and in the case of openjdk, some versions support suse SLES (enterprise server based on linux), and IBM AIX (UNIX derivative marketed for workstations and enterprise servers). Given that mongodb supports only linux, x86_64 windows, and mac, I think we have no reason to seek to actively support other platforms. Anyone smart and stubborn enough to setup java and mongodb on their custom os written in brainfuck for a mips SoC, would have absolutely zero trouble compiling one more library. Additionally, since I made this PR, it would be my responsibility to troubleshoot and assist with jnlua issues. Core gameplay development has stagnated for months, and we need a solution

Totally agreed, i've tested it personally and jnlua solves some problems that are currently in place. Its better to have something working on major platforms than something not working on any platform. Anyone on edge case platforms can build the needed libraries themselves.

**Comment by akatatsu27** [comment]
> I hope that the binary files of arm64

I've added binaries for arm32-linux and arm64-linux, but I have no means of testing. I would really appreciate it if you, or anyone else, could test its functionality. Trying to do the first mainQuest (type in the console ```quest add 35104 @<UID>) would be a good way to test. If you can finish the whole quest, that means it's working

**Comment by SpikeHD** [comment]
**One Two Three Four!**
JNLua gives us more!
**Five Six Seven Eight!**
JNLuas really great!

**Comment by alt3ri** [comment]
JNLua is love
JNLua is life

**Comment by Birdulon** [comment]
Closing by request.

Current project stance is to not introduce native dependencies (https://github.com/Grasscutters/Grasscutter/blob/development/CONTRIBUTING.md#code-content).

**Comment by pfyy** [comment]
Is it possible to create a modified version of luaj specifically for grasscutter?

I think the only problem is `org.luaj.vm2.lib.jse.JavaMethod`.
It demands the first argument of ScriptLib function to be userdata (`arg1.checkuserdata()`), which is not always the case e.g. `ScriptLib.GetEntityType` (#1703, 
#1725).

It might solve the problem if we simply rewrite this class.

[https://github.com/luaj/luaj/blob/master/src/jse/org/luaj/vm2/lib/jse/JavaMethod.java](https://github.com/luaj/luaj/blob/master/src/jse/org/luaj/vm2/lib/jse/JavaMethod.java)

```java
class JavaMethod extends JavaMember {

	static final Map methods = Collections.synchronizedMap(new HashMap());
	
	static JavaMethod forMethod(Method m) {
		JavaMethod j = (JavaMethod) methods.get(m);
		if ( j == null )
			methods.put( m, j = new JavaMethod(m) );
		return j;
	}
	
	static LuaFunction forMethods(JavaMethod[] m) {
		return new Overload(m);
	}
	
	final Method method;
	
	private JavaMethod(Method m) {
		super( m.getParameterTypes(), m.getModifiers() );
		this.method = m;
		try {
			if (!m.isAccessible())
				m.setAccessible(true);
		} catch (SecurityException s) {
		}
	}

	public LuaValue call() {
		return error("method cannot be called without instance");
	}

	public LuaValue call(LuaValue arg) {
		return invokeMethod(arg.checkuserdata(), LuaValue.NONE);
	}

	public LuaValue call(LuaValue arg1, LuaValue arg2) {
		return invokeMethod(arg1.checkuserdata(), arg2);
	}
	
	public LuaValue call(LuaValue arg1, LuaValue arg2, LuaValue arg3) {
		return invokeMethod(arg1.checkuserdata(), LuaValue.varargsOf(arg2, arg3));
	}
	
	public Varargs invoke(Varargs args) {
		return invokeMethod(args.checkuserdata(1), args.subargs(2));
	}
	
	LuaValue invokeMethod(Object instance, Varargs args) {
		Object[] a = convertArgs(args);
		try {
			return CoerceJavaToLua.coerce( method.invoke(instance, a) );
		} catch (InvocationTargetException e) {
			throw new LuaError(e.getTargetException());
		} catch (Exception e) {
			return LuaValue.error("coercion error "+e);
		}
	}
	
	/**
	 * LuaValue that represents an overloaded Java method.
	 * <p>
	 * On invocation, will pick the best method from the list, and invoke it.
	 * <p>
	 * This class is not used directly.  
	 * It is returned by calls to calls to {@link JavaInstance#get(LuaValue key)} 
	 * when an overloaded method is named.
	 */
	static class Overload extends LuaFunction {

		final JavaMethod[] methods;
		
		Overload(JavaMethod[] methods) {
			this.methods = methods;
		}

		public LuaValue call() {
			return error("method cannot be called without instance");
		}

		public LuaValue call(LuaValue arg) {
			return invokeBestMethod(arg.checkuserdata(), LuaValue.NONE);
		}

		public LuaValue call(LuaValue arg1, LuaValue arg2) {
			return invokeBestMethod(arg1.checkuserdata(), arg2);
		}
		
		public LuaValue call(LuaValue arg1, LuaValue arg2, LuaValue arg3) {
			return invokeBestMethod(arg1.checkuserdata(), LuaValue.varargsOf(arg2, arg3));
		}
		
		public Varargs invoke(Varargs args) {
			return invokeBestMethod(args.checkuserdata(1), args.subargs(2));
		}

		private LuaValue invokeBestMethod(Object instance, Varargs args) {
			JavaMethod best = null;
			int score = CoerceLuaToJava.SCORE_UNCOERCIBLE;
			for ( int i=0; i<methods.length; i++ ) {
				int s = methods[i].score(args);
				if ( s < score ) {
					score = s;
					best = methods[i];
					if ( score == 0 )
						break;
				}
			}
			
			// any match? 
			if ( best == null )
				LuaValue.error("no coercible public method");
			
			// invoke it
			return best.invokeMethod(instance, args);
		}
	}

}
`

**Comment by pfyy** [comment]
BTW, luaj is using MIT license and open source, which means modification to it is allowed.

**Comment by pfyy** [comment]
An evident but extremely dirty modification is to change

```java
	LuaValue invokeMethod(Object instance, Varargs args) {
		Object[] a = convertArgs(args);
		try {
			return CoerceJavaToLua.coerce( method.invoke(instance, a) );
		} catch (InvocationTargetException e) {
			throw new LuaError(e.getTargetException());
		} catch (Exception e) {
			return LuaValue.error("coercion error "+e);
		}
	}
```
to something like
```java
	LuaValue invokeMethod(Varargs args) {
		Object[] a = convertArgs(args);
		try {
			return CoerceJavaToLua.coerce( method.invoke(ScriptLoader.getScriptLib(), a) );
		} catch (InvocationTargetException e) {
			throw new LuaError(e.getTargetException());
		} catch (Exception e) {
			return LuaValue.error("coercion error "+e);
		}
	}
```

(I'm not a Java programmer, please do not laugh if I made some silly mistakes 😂)

**Pull request closed without merging**
