### PR TITLE
Add block game update option

### PR DESCRIPTION
**Pull request by krrr**
## Description
Implemented fake update check API to block game update, enable the game to be played without internet connetion. current mitmproxy script (and fiddler script i guess) require dns lookup and will establish conneciton with official server (without sending data though). so it must be used together with my mitmproxy script 

this option is disabled by default as it needed to modify config file in JRE: https://www.petefreitag.com/item/916.cfm ,
and i have only tested on my up-to-date 2.6 global client

## Issues fixed by this PR
https://github.com/Grasscutters/Grasscutter/issues/326
https://github.com/Grasscutters/Grasscutter/issues/664

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by krrr** [comment]
my mitmproxy script:

```python
"""yuanshen mitm. need improve."""
from mitmproxy import http
from mitmproxy import ctx
from mitmproxy.proxy import layer, layers


def load(loader):
    ctx.options.web_open_browser = False
    # We change the connection strategy to lazy so that next_layer happens before we actually connect upstream.
    ctx.options.connection_strategy = "lazy"
    ctx.options.upstream_cert = False
    ctx.options.ssl_insecure = True

    
def next_layer(nextlayer: layer.NextLayer):
    ctx.log(
        f"{nextlayer.context=}\n"
        f"{nextlayer.data_client()[:70]=}\n"
    )
    sni = nextlayer.context.client.sni
    if nextlayer.context.client.tls and sni and (sni.endswith("yuanshen.com") or sni.endswith("mihoyo.com") or sni.endswith("hoyoverse.com")):
        ctx.log('sni:' + sni)
        nextlayer.context.server.address = ("127.0.0.1", 443)


def request(flow: http.HTTPFlow) -> None:
    # pretty_host takes the "Host" header of the request into account,
    # which is useful in transparent mode where we usually only have the IP
    # otherwise.
    if flow.request.pretty_url.startswith('http://log-upload-os.mihoyo.com'):
        flow.response = http.Response.make(
            404,  # (optional) status code
            b"404 not found",  # (optional) content
            {"Content-Type": "text/html"}  # (optional) headers
        )
        return

```

**Comment by ghost** [comment]
All of this is completely unnecessary. We should remove `data\query_cur_region.txt` and just let server build one dynamically like it does right now when file is missing.

For a quick test, can you drop `query_cur_region.txt` from `data` directory, restart server and then start game without any of your modifications? I can not reproduce any attempt for connection to `autopatchhk.yuanshen.com` in this way since client is not given any source to download data from nor it is told what version server expects, so it just skips whole update process.

**Comment by mcxiaoke** [comment]
grasscutter should block all requests to mhy official server, should rewrite autopatchhk.yuanshen.com urls to local server in query_cur_region

**Comment by ghost** [comment]
There is no reason to provide them at all

**Comment by krrr** [comment]
> All of this is completely unnecessary. We should remove `data\query_cur_region.txt` and just let server build one dynamically like it does right now when file is missing.
> 
> For a quick test, can you drop `query_cur_region.txt` from `data` directory, restart server and then start game without any of your modifications? I can not reproduce any attempt for connection to `autopatchhk.yuanshen.com` in this way since client is not given any source to download data from nor it is told what version server expects, so it just skips whole update process.

Your argument is complete nonsense. Should you ever tried yourself, you will easily find that the game refuse to login because of update failure after removing the file. error code 4205.

**Comment by krrr** [comment]
> There is no reason to provide them at all

What's your problem?

**Comment by krrr** [comment]
> grasscutter should block all requests to mhy official server, should rewrite autopatchhk.yuanshen.com urls to local server in query_cur_region

it shounld not be enabled by default. it requires modifying java runtime config file to enable TLSv1 when encryption enabled, otherwise login will fail.
Alternatively, let dispatch server bind other plain HTTP port when encryption enabled, and handle game update API using that port, to get around TLSv1 problem

**Comment by ghost** [comment]
If you look at `RegionInfo.proto`, you will notice that only fields 1, 2 and 23 are necessary. Default `query_cur_region.txt` we provide is a copy from vanilla server and contains 1, 2, 3, 7, 8, 9, 10, 12, 14, 18, 19, 20, 22, 23, 24, 26, 27, 27, 31, 32, 33. We override fields 1, 2 and 23 however we leave rest of them as-is. 

Of these, 8 and 9 give client full URL to `autopatchhk.yuanshen.com`, while 12 give `2.6_live` portion. Fields 14 and 18 tell client to which version it should update itself while 19 and 20 give MD5s for them. I won't bother you with details of rest of fields, they contain additional URLs for stuff like payment portal or feedback.

Since we do not support any of this, we should not supply these fields and the client will ignore them. Similarly, not supplying update version and resources URL will have client skip update and just join server using whatever version it is at.

**Pull request closed without merging**
