### PR TITLE
[Ready]Replace deprecated KCP library

### PR DESCRIPTION
**Pull request by zhaodice**
## Description
Replace deprecated KCP library with mine which has being maintained by me 

Library source(Modify to work with grasscutter):
https://github.com/zhaodice/grasskcpper

Original library: 
https://github.com/l42111996/java-Kcp

**You can replace jar file with your build**

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by AkkaXdXd** [comment]
Hello, I have committed a pr #1229, implementation element burst invincible time, using the reflection to get the rest of kcp, to calculate the end time of element burst, view the source of this kcp lib. I haven't found any method to get the RTT of the current kcp.
你好，我提交了一个pr #1229 ，实现角色大招期间无敌的功能，其中用反射来获取Kcp的rtt来计算延迟，用于精准计算大招结束时间，看了下这个kcp的源码，好像也没有直接的方法能拿到rtt。

**Comment by zhaodice** [comment]
> Hello, I have committed a pr #1229, implementation element burst invincible time, using the reflection to get the rest of kcp, to calculate the end time of element burst, view the source of this kcp lib. I haven't found any method to get the RTT of the current kcp. 你好，我提交了一个pr #1229 ，实现角色大招期间无敌的功能，其中用反射来获取Kcp的rtt来计算延迟，用于精准计算大招结束时间，看了下这个kcp的源码，好像也没有直接的方法能拿到rtt。

什么是rtt

**Comment by AkkaXdXd** [comment]
> > Hello, I have committed a pr #1229, implementation element burst invincible time, using the reflection to get the rest of kcp, to calculate the end time of element burst, view the source of this kcp lib. I haven't found any method to get the RTT of the current kcp. 你好，我提交了一个pr #1229 ，实现角色大招期间无敌的功能，其中用反射来获取Kcp的rtt来计算延迟，用于精准计算大招结束时间，看了下这个kcp的源码，好像也没有直接的方法能拿到rtt。
> 
> 什么是rtt

往返时延

**Comment by zhaodice** [comment]
如果确实有需求，我可以在源码里再添加一项API用于被称之为rtt的功能，和grasscutter对接，反射是坏思想，所以不建议反射。

**Comment by AkkaXdXd** [comment]
嗯，因为kcp上是有一个平均时延字段的srtt, 这个字段我觉得用来当rtt也够了，之前的kcp lib，要从UkcpChannel 到Ukcp再到kcp来获取这个。看melledy怎么回复吧

**Comment by zhaodice** [comment]
> 嗯，因为kcp上是有一个平均时延字段的srtt, 这个字段我觉得用来当rtt也够了，之前的kcp lib，要从UkcpChannel 到Ukcp再到kcp来获取这个。看melledy怎么回复吧

看一下这样如何？

**Comment by zhaodice** [comment]
其中 ,你可以用 `KcpTunnel.getSrtt()`  ，而 KcpTunnel 被 GameSession 持有

**Comment by AkkaXdXd** [comment]
好的 我看到了 感谢支持，有这个的话，WorldPlayerRTTNotify 也可以使用实际的延迟了，现在是固定的10ms

**Comment by zhaodice** [comment]
> 好的 我看到了 感谢支持，有这个的话，WorldPlayerRTTNotify 也可以使用实际的延迟了，现在是固定的10ms

我印象里grasscuter的java版本蛮高的，而新版的java新增了安全机制，好像禁止了一些未经授权的反射行为，虽然不清楚你是怎么成功的，但它肯定不是长久之计便是。

**Comment by AkkaXdXd** [comment]
这样嘛，工作一直用java8，不太清楚高版本的一些特性，看了下使用SecurityManager 好像是能禁止反射
[java16好像是禁止反射了](https://blogs.oracle.com/javamagazine/post/a-peek-into-java-17-continuing-the-drive-to-encapsulate-the-java-runtime-internals)，我用的是reflections库，它好像是用asm实现的，具体细节你可以谷歌下。

**Comment by zhaodice** [comment]
> 这样嘛，工作一直用java8，不太清楚高版本的一些特性，看了下使用SecurityManager 好像是能禁止反射 [java16好像是禁止反射了](https://blogs.oracle.com/javamagazine/post/a-peek-into-java-17-continuing-the-drive-to-encapsulate-the-java-runtime-internals)，我用的是reflections库，它好像是用asm实现的，具体细节你可以谷歌下。

嗯，对了，如果确定要依赖我的pr，你可以把你的pr设为草稿状态，等待我这条pr并入后，你再拉下来继续更新你的pr也许符合正常的开发顺序。

**Comment by AkkaXdXd** [comment]
嗯 好，看melledy怎么回复了，如果要考虑延迟，我就设为草稿状态，等你提交之后rebase修改提交了再打开

**Comment by ghost** [comment]
Someone will need to test this throughly. Any volunteers?

**Comment by zhaodice** [comment]
> Someone will need to test this throughly. Any volunteers?

I have tow devices to login server, no problem yet, may it needs huge scale test.

**Comment by akbaryahya** [comment]
I testing this, first time server was running it was fine without any error messages again but when I tried to exit game and then log in again it became a long white loading screen until I got a timeout message and I had to restart server so I could log in normally again. I'm testing this from jar file [Grasscutter/actions/runs/2478530480](https://github.com/Grasscutters/Grasscutter/actions/)

**Comment by zhaodice** [comment]
> I testing this, first time server was running it was fine without any error messages again but when I tried to exit game and then log in again it became a long white loading screen until I got a timeout message and I had to restart server so I could log in normally again. I'm testing this from jar file

I found a problem that loading progress will stay in rock element, in fact , this problem was found in old kcp library, you needn't restart server, just restart client.

**Comment by zhaodice** [comment]
> I testing this, first time server was running it was fine without any error messages again but when I tried to exit game and then log in again it became a long white loading screen until I got a timeout message and I had to restart server so I could log in normally again. I'm testing this from jar file [Grasscutter/actions/runs/2478530480](https://github.com/Grasscutters/Grasscutter/actions/)

I'm testing this from jar file [Grasscutter/actions/runs/2478530480](https://github.com/Grasscutter/actions/runs/2478530480)
No problem emerged with second login.

**Comment by zhaodice** [comment]
but I think it is caused by packs loss, so I will change `resend` 2 to 5

**Comment by zhaodice** [comment]
It seems to be stable when I edit its MTU to 1200

**Comment by TardisXE** [comment]
我在测试时遇到了多次登录后白屏的问题，需要重启服务器才可能解决。使用https://github.com/Grasscutters/Grasscutter/actions/runs/2480347924

**Comment by zhaodice** [comment]
> 我在测试时遇到了多次登录后白屏的问题，需要重启服务器才可能解决。使用https://github.com/Grasscutters/Grasscutter/actions/runs/2480347924

问题已经知晓了，我现在正在排查，主要是这个问题比较...幽灵，每次时有时没有的，就很烦

**Comment by zhaodice** [comment]
我在想是什么地方阻塞了...我加个线程池看一下

**Comment by zhaodice** [comment]
> 我在测试时遇到了多次登录后白屏的问题，需要重启服务器才可能解决。使用https://github.com/Grasscutters/Grasscutter/actions/runs/2480347924

对了，请问你的测试环境是本地（127.0.0.1）吗

**Comment by akbaryahya** [comment]
Testing with 2480353273, now I can't even log in at all
ts34

**Comment by TardisXE** [comment]
> > 我在测试时遇到了多次登录后白屏的问题，需要重启服务器才可能解决。使用https://github.com/Grasscutters/Grasscutter/actions/runs/2480347924
> 
> 对了，请问你的测试环境是本地（127.0.0.1）吗

我是在云服务器上搭建的Grasscutters，并不在本地

**Comment by zhaodice** [comment]
那芭比Q了，我本地测的测不出来，我丢服务器上看看...

**Comment by zhaodice** [comment]
According to a lot of test, bad package is ineluctable. a problem is that bad package emerged in crucial login, login screen will freeze.
经过多次测试我发现坏包是不可避免的，现在的一个问题是只要坏包出现在关键的登陆包上，就会卡登陆

**Comment by zhaodice** [comment]
so now we need a timeout-detector, it can help server to see whether user logins, if it takes too much time, server should let client re-login( actually, this problem caused by Grasscutter rather than KCP library)
因此现在需要加一条超时逻辑，判断用户是否真正进入服务器，如果超时就发一个断开包让用户尽快重新登陆（其实这应该是Grasscutter的问题而不是这个协议库的问题了）

**Comment by zhaodice** [comment]
@akbaryahya @TardisLX
may you try again? I think it is no problem except ineluctable bad package(because it is UDP)
可以再试一次吗？我觉得除了因为UDP偶尔坏几个数据包之外没有什么问题

**Comment by GanyusLeftHorn** [comment]
Just tried it myself with the newest build (2480713141). On first login, I get multiple errors of the form

```
10:29:44 <ERROR:GameSession> Bad Data Package Received: got 11627 ,expect 17767
10:29:49 <ERROR:GameSession> Bad Data Package Received: got -4236 ,expect 17767
10:29:49 <ERROR:GameSession> Bad Data Package Received: got -7393 ,expect 17767
10:29:51 <ERROR:GameSession> Bad Data Package Received: got -32484 ,expect 17767
10:29:52 <ERROR:GameSession> Bad Data Package Received: got -13576 ,expect 17767
```

On second login, I get a white screen.

**Comment by zhaodice** [comment]
> On second login, I get a white screen.

Error is normal, udp is not reliable, without restarting server, how about third login?

**Comment by akbaryahya** [comment]
testing with 2480713141 still time out after logging in for second time
t39
btw 3rd login still can't work

**Comment by zhaodice** [comment]
> testing with 2480713141 still time out after logging in for second time t39 btw 3rd login still can't work

Edit config.json , change `"debugLevel": "NONE",` to "debugLevel": "ALL",

I want to get more infomation

**Comment by GanyusLeftHorn** [comment]
> Error is normal, udp is not reliable

Not sure about that. When I log bad packets with the existing KCP implementation, I get a single one during login. With the new one, I get between five and ten.

> how about third login?

Doesn't work either. I have to restart the server to make it work again.

**Comment by zhaodice** [comment]
I got it, I will try decrease bad package count first

**Comment by akbaryahya** [comment]
> > testing with 2480713141 still time out after logging in for second time t39 btw 3rd login still can't work
> 
> Edit config.json , change `"debugLevel": "NONE",` to "debugLevel": "ALL",
> 
> I want to get more infomation

this is data log after trying to log in a second time
[latest.log](https://github.com/Grasscutters/Grasscutter/files/8884521/latest.log)

**Comment by zhaodice** [comment]
I think I have fixed this fucking bug which is wrong sequence of calling among `KcpListener`!
I have tested 10 times, there is no longer problem.
我终于干死这个傻逼bug了，原来是KcpListener的调用顺序出了问题！
我试了10次，没有任何问题了，稳如老狗
@akbaryahya @kyoko12

**Comment by zhaodice** [comment]
image

**Comment by zhaodice** [comment]
@TardisLX 现在应该没有问题了，麻烦有时间再看看吧，巨大感谢>_<

**Comment by zhaodice** [comment]
Finally,thanks every volunteers for this testing!

**Comment by akbaryahya** [comment]
yay it's working now, now i'll try it on live server see it's working fine

**Comment by zhaodice** [comment]
image
I have uploaded jar to server for testing, it looks stable

**Comment by TardisXE** [comment]
> @TardisLX 现在应该没有问题了，麻烦有时间再看看吧，巨大感谢>_<

目前使用确实很好很稳定，辛苦

**Comment by zhaodice** [comment]
> > @TardisLX 现在应该没有问题了，麻烦有时间再看看吧，巨大感谢>_<
> 
> 目前使用确实很好很稳定，辛苦

是啊，甚至现有的私服毁灭者（专门用来攻击私服的压测工具）都失效了XD

**Comment by zhaodice** [comment]
I use follow logic to ensure conv id security and unique
```
//generate unique convId
synchronized (channelManager) {
    do {
        convId = secureRandom.nextLong();
    } while (channelManager.convExists(convId) || handshakeWaitersFind(convId) != null);
}
```

**Comment by zhaodice** [comment]
All done, I think I have nothing to do until new problem emerged
(Welcome you to test the new one and be feel free to bring your feedback here!)

**Comment by GanyusLeftHorn** [comment]
I've tested it for around two hours now. Seems to be working fine. However, I have only tested it locally, in a single player scenario. Someone should probably also test it with multiple players connected to the server, maybe even in co-op.

**Comment by TardisXE** [comment]
> I've tested it for around two hours now. Seems to be working fine. However, I have only tested it locally, in a single player scenario. Someone should probably also test it with multiple players connected to the server, maybe even in co-op.

I have been testing it for more than ten hours, and no errors have been found on multiple players and on remote servers.

**Comment by akbaryahya** [comment]
since 16 hours ago my two servers have had no more problems and even better, there are no session duplications or stuck sessions that cause online users to become 1000+ even though there are actually not that many online like only 100-200. I think it's ready ;)

**Comment by zhaodice** [comment]
> Someone will need to test this throughly. Any volunteers?

According to above,I think it is ready

**Comment by zhaodice** [comment]
Finally,I have improved connection subsequence, commit: 
https://github.com/zhaodice/grasskcpper/commit/a80044ac83473b63d2613598327d63303497ca5d

**Review by ghost — APPROVED** [review]

**Pull request merged**
