### PR TITLE
3.4.0 proto update

### PR DESCRIPTION
**Pull request by Hiro420**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature???
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Hiro420** [comment]
Build failed only because missing gradle.properties lollll

**Review by 4Benj — CHANGES_REQUESTED** [review]
Please only commit protos that already exists in Grasscutter or are needed for the update.

**Comment by Hiro420** [comment]
with the new proto structure it wont work unless you want over 2k errors lol

**Comment by Hiro420** [comment]
or if you want to rewrite most of the ps

**Comment by Simplxss** [comment]
if u have difficulty deleting the useless protos, i could help u.

or u want to make it yourself, the following script may help you.

https://gitlab.com/YuukiPS/GC-Proto/-/blob/3.4-Unknown/op.js

**Comment by lilmayofuksu** [comment]
> with the new proto structure it wont work unless you want over 2k errors lol
> or if you want to rewrite most of the ps

That doesn't make any sense. Unused protos can be easily deleted.

**Comment by Bannyfelt13** [comment]
skill issues

**Comment by KingRainbow44** [comment]
closing due to duplicate of #2041 and conflicts

**Pull request closed without merging**
