### PR TITLE
Implementing the `Player Show Avatars`

### PR DESCRIPTION
**Pull request by Konoyoru435**
In a nutshell: Player avatars showcase is available, but not tested in multiplayer.

Working list and main ideas:
- [x] Handle `UpdatePlayerShowAvatarListReq` packet from client, get `IsShowAvatar` and `ShowAvatarIdListList` data from it, save it, and return `UpdatePlayerShowAvatarListRsp` packet;
- [x] Will return the avatars show information in `getSocialDetail` of `Player`.

Protos:
- `UpdatePlayerShowAvatarListReq.proto`
- `UpdatePlayerShowAvatarListRsp.proto`

PR Here: https://github.com/Grasscutters/Grasscutter-Protos/pull/10

Image:
avatars

### CODE REVIEW

**Comment by Yazawazi** [comment]
wtf Why are my previous commits here too?

**Comment by alt3ri** [comment]
submit a PR to Protos please

**Comment by Yazawazi** [comment]
> submit a PR to Protos please

OK！(。•̀ᴗ-)✧

**Comment by Yazawazi** [comment]
I have submitted a PR in the `Grasscutter-Protos` repo, and since my last PR was not closed, it is still at https://github.com/Grasscutters/Grasscutter-Protos/pull/10.

**Comment by ghost** [comment]
> I have submitted a PR in the `Grasscutter-Protos` repo, and since my last PR was not closed, it is still at [Grasscutters/Grasscutter-Protos#10](https://github.com/Grasscutters/Grasscutter-Protos/pull/10).

You dont need to PR to that repo anymore, the protos have been moved back to this repo.

**Comment by Yazawazi** [comment]
> > I have submitted a PR in the `Grasscutter-Protos` repo, and since my last PR was not closed, it is still at [Grasscutters/Grasscutter-Protos#10](https://github.com/Grasscutters/Grasscutter-Protos/pull/10).
> 
> You dont need to PR to that repo anymore, the protos have been moved back to this repo.

Thank you, I got it.

**Comment by WetABQ** [comment]
> submit a PR to Protos please

after #226, contributors will no longer need to upload new protos to https://github.com/Grasscutters/Grasscutter-Protos/pull/10, but need to put them in the main proto folder under the `/proto`

**Comment by memetrollsXD** [comment]
It shouldn't be different in multiplayer.. to be tested

**Comment by Yazawazi** [comment]
I can't find a player I can test multiplayer with, or are any of you willing to test?

**Comment by ghost** [comment]
You dont need to be in multiplayer, just make a 2nd account and add your 1st account to your friends list.

**Comment by Yazawazi** [comment]
Got it!

**Comment by Yazawazi** [comment]
`java.lang.NullPointerException` sorry, will fix it latter

**Comment by ghost** [comment]
I assume its because the avatars need to be loaded from the database if the player is offline.

**Comment by Yazawazi** [comment]
Yes, players have to read data from the database when they are offline, fixed and tested.

**Review by ghost — APPROVED** [review]

**Pull request merged**
