### PR TITLE
Proper Dungeon Rewards

### PR DESCRIPTION
**Pull request by GanyusLeftHorn**
## Description

Implementation of dungeon rewards. Adds handling for dungeon drops. Drops can be configured in a new file `DungeonDrop.json`, which for each dungeons allows the definition of multiple drop groups, each of which can define
- `counts`: how many items are dropped from that group (as a range),
- `probabilities`: a probability distribution for the number of drops (defaults to uniform if not specified),
- `items`: a list of items that can drop in this group,
- `itemProbabilities`: a probability distribution over the possible items (defaults to uniform if not specified),
- `mpDouble`: whether the amout of items dropped in this group should be doubled in multiplayer (mainly intended for friendship exp).

Included dungeons:
- Forsaken Rift (all days)
- Taishan Mansion (all days)
- Violet Court (all days)
- Cecilia Garden (all days)
- Hidden Palace of Lianshan Formula (all days)
- Court of Flowing Sand (all days)
- Clear Pool of Mountain Cavern
- Domain of Guyun
- Midsummer Courtyard
- Momiji-Dyed Court
- Ridge Watch
- Slumbering Court
- The Lost Valley
- Valley of Remembrance

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Cardgodk** [comment]
How to enable this function

**Comment by GanyusLeftHorn** [comment]
It's work in progress. Once it's done and merged, it will be enabled automatically for all dungeons that have rewards defined for them.

**Comment by Cardgodk** [comment]
> 这是正在进行的工作。完成并合并后，将自动为所有为其定义奖励的地下城启用它。

OK, that's good

**Comment by Cardgodk** [comment]
Can those dungeons that can't get rewards normally only wait for scripts to repair

**Comment by GanyusLeftHorn** [comment]
If you mean the dungeons that currently don't let you claim rewards because the challenge doesn't end or the barrier doesn't despawn, then yes, that is a script issue. If you mean the dungeons that are currently missing drop data, I'm gonna add these before marking this PR ready for review.

**Comment by Cardgodk** [comment]
> 



> 如果你的意思是目前不允许你获得奖励的地下城，因为挑战没有结束或障碍没有消失，那么是的，这是一个脚本问题。如果你指的是目前缺少掉落数据的地下城，我将在标记此PR准备审查之前添加这些。

OK, I mean the dungeons that can't complete the challenge. Thank you for your contribution

**Comment by Cardgodk** [comment]
> > 
> 
> > 如果你的意思是目前不允许你获得奖励的地下城，因为挑战没有结束或障碍没有消失，那么是的，这是一个脚本问题。如果你指的是目前缺少掉落数据的地下城，我将在标记此PR准备审查之前添加这些。
> 
> OK, I mean the dungeons that can't complete the challenge. Thank you for your contribution

抱歉,我的英文不太好，只能靠翻译

**Comment by lingzn12** [comment]
非常期待功能的增加

**Review by ghost — APPROVED** [review]

**Comment by 928926281** [comment]
Once this is added, the gacha cannot be used. When entering the Gacha, it will get stuck and cannot perform any operations.
Even if I modified the prize pool it didn't work.

**Comment by Birdulon** [comment]
> Once this is added, the gacha cannot be used. When entering the Gacha, it will get stuck and cannot perform any operations. Even if I modified the prize pool it didn't work.

It's actually the commit before this was merged that caused that. The current `development` branch was reset to before that commit, so if you force pull from `development` those issues will disappear.

**Pull request merged**
