### PR TITLE
Init fixed KCP library instead of buggy kcp.jar (del from lib)

### PR DESCRIPTION
**Pull request by BiosNod**
## Description

Replace KCP library in GC to this https://github.com/YuFanXing/grasskcpper

## Issues fixed by this PR
Because GC use a partially broken KCP library with some errors (for my case I faced it when I write a KCP Proxy inside GC)
I replaced GC KCP library to this and all KCP features work fine instead of the current GC KCP lib 

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by zhaodice** [comment]
Mellody said that it is not allowed to put another project's source code into this project(of course, I am not sure whether is ok or not now )
see: https://github.com/Grasscutters/Grasscutter/pull/1219

**Comment by BiosNod** [comment]
I think it will be a funniest waste of time to rewrite a whole library in some different way for the sake of following the covenants of Melledy. Ask Melledy again, If he doesn't answer and doesn't answer in the future, I believe that you can reconsider the rules

Ask ChatGPT to rewrite it in another way will be possible goofy solution :D

Guess it will be closed without merging, so, please fix KCP by another possible way, GC developers

**Comment by zhaodice** [comment]
> I think it will be a funniest waste of time to rewrite a whole library in some different way for the sake of following the covenants of Melledy. Ask Melledy again, If he doesn't answer and doesn't answer in the future, I believe that you can reconsider the rules
> 
> Ask ChatGPT to rewrite it in another way will be possible goofy solution :D
> 
> Guess it will be closed without merging, so, please fix KCP by another possible way, GC developers

Mellody seems deleted his account, so may never get respond from him, we can wait current maintainer.

**Review by KingRainbow44 — CHANGES_REQUESTED** [review]
Please include the library as a **JAR file.**

**Comment by KingRainbow44** [comment]
closing due to inactivity; feel free to make a new PR if you can complete the requested changes!

**Pull request closed without merging**
