### PR TITLE
improve server side command line input

### LINKED ISSUE #301: [Latest Dev] Server command input cannot accept Non-ASCII characters.
**Describe the bug**
When using /sendmail, the console cannot accept non-ascii characters. But in-game can be handled correctly.

**To Reproduce**
Type non-ascii characters in server console.

**Expected behavior**
Non-ascii characters should also be accepted.

**Screenshots**
image
image
image

**Desktop (please complete the following information):**
 - OS: Windows 11, Running JDK 18
 - Version Dev

**Additional context**

### LINKED ISSUE #302: Arrow key not working behind tmux
Linux Ubuntu 20.04, running grasscutter with tmux, pressing arrow keys would only put `^[[A` or `^[[B`. Should I remap or whatever to have arrow keys working?

### PR DESCRIPTION
**Pull request by Qiuk17**
fixed #301 #302 with JLine3

### CODE REVIEW

**Review by KingRainbow44 — APPROVED** [review]
looks good, needs testing be4 merge

**Comment by Qiuk17** [comment]
tested on windows(cmd & pwsh) and macos and it works fine.
not tested on linux.

**Comment by Qiuk17** [comment]
pwsh + windows terminal
winterm+pwsh

also works in console
winconsole+cmd

**Comment by Qiuk17** [comment]
Hi, @KingRainbow44 .
I have tested on as many platforms as possible.
- Windows
  - console host + cmd.exe (OK)
  - terminal + pwsh/cmd (OK)
  - embedded terminal in Idea (**Usable**, but it cannot handle Ctrl-C and Ctrl-D, causing an infinite loop. It also reacts slowly (characters display on screen will delay for about 1 sec))
- Linux (CentOS 7 x64)
  - iterm2 + zsh (over ssh) (OK)
- MacOS (12.3 aarch64)
  - iterm2 + zsh (OK)

This pr also fixes #403 **to some extent**. ~~But when printing multiline logs, the command you typed is stilled covered.~~
I think this is ready to merge.

**Review by Ljzd-PRO — APPROVED** [review]

**Comment by Qiuk17** [comment]
> This pr also fixes #403 **to some extent**. But when printing multiline logs, the command you typed is stilled covered.

fixed now.

**Review by Ljzd-PRO — APPROVED** [review]

**Review by memetrollsXD — APPROVED** [review]
Tested with git bash, works

**Comment by DancingSnow0517** [comment]
why don't work in my server's CMD
can't input anything to the console

**Comment by Qiuk17** [comment]
> why don't work in my server's CMD can't input anything to the console

any screenshots？@DancingSnow0517

**Comment by DancingSnow0517** [comment]
image

**Comment by DancingSnow0517** [comment]
can‘t input anything

**Comment by Qiuk17** [comment]
@DancingSnow0517 
dm me on discord `Presiareen#8171`
i never test on a remote windows server.

**Pull request merged**
