### PR TITLE
Added past gacha system

### PR DESCRIPTION
**Pull request by YinBuLiao**

### CODE REVIEW

**Comment by Scirese** [comment]
建议加上英文注释,还有，卡池应该是“banner”
---------------
It is recommended to add English annotations as well.

**Comment by YinBuLiao** [comment]
> ## 建议加上英文注释,还有，卡池应该是“banner”
> It is recommended to add English annotations as well.

你确定是banner？banner不是横幅吗

**Comment by Scirese** [comment]
> > ## 建议加上英文注释,还有，卡池应该是“banner”
> > It is recommended to add English annotations as well.
> 
> 你确定是banner？

是，我确定

**Comment by Scirese** [comment]
其实我建议你关掉这个pr，这个没必要合到这里。让需要的人自己添加就好了

Actually I recommend you to close the pr,its not necessary to merge it here.Just let these who need these banners to add it by themselves.

**Pull request closed without merging**
