### PR TITLE
Added another general troubleshooting 

### PR DESCRIPTION
**Pull request by SinoAHpx**

### CODE REVIEW

**Review by lunaticwhat — CHANGES_REQUESTED** [review]
* Java 8 JDK [mirror link since Oracle required an account to download old builds](https://mirrors.huaweicloud.com/java/jdk/8u202-b08/)

**Comment by SinoAHpx** [comment]
my modification is already use that link tho

**Comment by lunaticwhat** [comment]
yeah but I just put more explaination on it 😊

**Comment by SinoAHpx** [comment]
done!

**Review by KingRainbow44 — APPROVED** [review]
works!

**Pull request merged**
