### PR TITLE
[BREAKING CHANGE] Auto spawn all gadgets & monsters with some *anime game* Lua

### PR DESCRIPTION
**Pull request by WetABQ**
I've tested in-game, all things work fine

**Kotlin has been used** in this project

**Breaking changes have been included** in this pr (I've re-written all entity related classes)

Before u run this pr, ur required to add the *anime game* Lua resources

image
image
image
image
image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by mmnt1337** [comment]
"all gadgets" include any grass spawn?

**Comment by WetABQ** [comment]
> "all gadgets" include any grass spawn?

it seems like "grass spawn" has been already existed before this pr.

**Review by ghost — CHANGES_REQUESTED** [review]
Please use only java for this pull request to be accepted.

**Comment by mahaoqqsx** [comment]
小工具如何生成，启动闪退

**Comment by yangjiahao0036** [comment]
the monsters is god.I was seckilled by it.

**Comment by 9588A9588** [comment]
> 怪物是上帝。我被它秒杀了。

+1

**Comment by xiu920411** [comment]
> the monsters is god.I was seckilled by it.

血量变为1，无法回血，切换到蒙德城直接卡死

**Comment by memetrollsXD** [comment]
Do you mean JSONs instead of Lua files? I will only accept if there are no direct references to the publishers "private codes"

**Comment by alt3ri** [comment]
yea, u have to get the json instead. This got me awhile

**Comment by xiu920411** [comment]
> Do you mean JSONs instead of Lua files? I will only accept if there are no direct references to the publishers "private codes"

Lua is just a folder name, and the script file is JSON

**Comment by alt3ri** [comment]
It's because he said "Lua resources", so we thought that we need Lua files for this.

**Comment by WetABQ** [comment]
> > the monsters is god.I was seckilled by it.
> 
> 血量变为1，无法回血，切换到蒙德城直接卡死

i will fix it later

**Comment by ClayCoffee** [comment]
Exception in thread "main" org.reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured
        at org.reflections.Store.get(Store.java:39)
        at org.reflections.Store.get(Store.java:61)
        at org.reflections.Store.get(Store.java:46)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:429)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416)
        at emu.grasscutter.command.CommandMap.scan(CommandMap.java:147)
        at emu.grasscutter.command.CommandMap.<init>(CommandMap.java:19)
        at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:60)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:80)

**Comment by alt3ri** [comment]
> Exception in thread "main" org.reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured at org.reflections.Store.get(Store.java:39) at org.reflections.Store.get(Store.java:61) at org.reflections.Store.get(Store.java:46) at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:429) at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416) at emu.grasscutter.command.CommandMap.scan(CommandMap.java:147) at emu.grasscutter.command.CommandMap.(CommandMap.java:19) at emu.grasscutter.server.game.GameServer.(GameServer.java:60) at emu.grasscutter.Grasscutter.main(Grasscutter.java:80)

Check the Issues section. This is Pull requests.

**Comment by WetABQ** [comment]
> > the monsters is god.I was seckilled by it.
> 
> 血量变为1，无法回血，切换到蒙德城直接卡死

Fixed

**Comment by WetABQ** [comment]
Known Issues: 
the monster would repeated refresh and hard to die.
~`stats` command will lose effect in short-time~ fixed

**Comment by Ryaang** [comment]
> Known Issues: the monster would repeated refresh and hard to die. `stats` command will lose effect in short-time

还有哨塔炸药木箱什么的被破坏之后又立刻刷新，破坏三四次之后不刷新

**Comment by WetABQ** [comment]
> > Known Issues: the monster would repeated refresh and hard to die. `stats` command will lose effect in short-time
> 
> 还有哨塔炸药木箱什么的被破坏之后又立刻刷新，破坏三四次之后不刷新

it's beacause we have not processed those of events yet, we need to call Lua function and all logics of u've mentioned in ur comments are in there

currently, @Melledy would not merge this pr yet, since Kotlin has been included in this pr. They want the pure Java project instead of mixing with Java and Kotlin

plz wait for the actual Lua executing, this pr is just parsing the Json instead of the real Lua.

**Comment by hbj2457** [comment]
大佬，有没有教程啊，我构建了新的grasscutter，但是不会自动刷怪

**Comment by QiE2035** [comment]
Could you only use java? I think Kotlin is better to use, but Kotlin have a little ... difficult? (or say more people use java better than kotlin

p.s. just an personal advice

**Comment by WetABQ** [comment]
> 

PR is welcomed, u could convert it into java and I'll accept it

**Comment by WetABQ** [comment]
> Could you only use java? I think Kotlin is better to use, but Kotlin have a little ... difficult? (or say more people use java better than kotlin
> 
> p.s. just an personal advice

PR is welcomed, u could convert it into java and I'll accept it

**Comment by cxfm666** [comment]
Exception in thread "main" java.lang.NullPointerException: directory.listFiles() must not be null
        at emu.grasscutter.data.SceneDataLoader.init(SceneDataProvider.kt:31)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:56)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:69)

**Comment by WetABQ** [comment]
> Exception in thread "main" java.lang.NullPointerException: directory.listFiles() must not be null at emu.grasscutter.data.SceneDataLoader.init(SceneDataProvider.kt:31) at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:56) at emu.grasscutter.Grasscutter.main(Grasscutter.java:69)

Before u run this pr, ur required to add the *anime game* Lua resources

**Comment by WetABQ** [comment]
> A project use both kotlin and java is possible. And convert java to kotlin is simple.

second that

**Comment by WetABQ** [comment]
due to introducing Kotlin as 2nd lang of this project, @Melledy would not accept this pr, thus I'll close it and wait for Java version

**Pull request closed without merging**
