### PR TITLE
Repair the treasure chest

### PR DESCRIPTION
**Pull request by millet6**
修复纪行自选 宝匣 Repair the self selected treasure box of the Chronicle

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by millet6** [comment]
QQ截图20220806211349
让它们正常得到物品 Let them get the goods normally

**Review by xing1225 — APPROVED** [review]

**Comment by Birdulon** [comment]
Weapon selection seems to work without this PR, talent book selection doesn't work with or without this PR.
image

**Comment by millet6** [comment]
> Weapon selection seems to work without this PR, talent book selection doesn't work with or without this PR. image

My local test is normal

**Comment by GanyusLeftHorn** [comment]
`ShopChestBatchUse.json` is not used by the battle pass system. Changing anything there will not fix (or break) anything related to BP.

**Comment by Birdulon** [comment]
Issue was fixed by #1634

**Pull request closed without merging**
