### PR TITLE
Refactor dispatch server

### PR DESCRIPTION
**Pull request by MlgmXyysd**
* In this way, we only need to open two ports

### CODE REVIEW

**Comment by ghost** [comment]
Consider making it a config option to merge servers since there are still people using fiddler to connect, including me.

**Comment by MlgmXyysd** [comment]
> Consider making it a config option to merge servers since there are still people using fiddler to connect, including me.

It's not as good as updating Fiddler script

**Comment by lunaticwhat** [comment]
I'm still using Fiddler too. if you want implement this I think it should be another branch or at least in another method to run the server.

**Comment by MlgmXyysd** [comment]
> I'm still using Fiddler too. if you want implement this I think it should be another branch or at least in another method to run the server.

Actually just need to rewrite the fiddler script, which itself is outdated before this PR.

**Comment by lunaticwhat** [comment]
oh that's cool. sorry I didnt read fiddler script need to be updated

**Comment by MlgmXyysd** [comment]
> Consider making it a config option to merge servers since there are still people using fiddler to connect, including me.

The rewritten Fiddler script is here. Now there is no problem.
```
import Fiddler;
var list = [
	"api-os-takumi.mihoyo.com",
	"hk4e-api-os-static.mihoyo.com",
	"hk4e-sdk-os.mihoyo.com",
	"dispatchosglobal.yuanshen.com",
	"osusadispatch.yuanshen.com",
	"account.mihoyo.com",
	"log-upload-os.mihoyo.com",
	"dispatchcntest.yuanshen.com",
	"devlog-upload.mihoyo.com",
	"webstatic.mihoyo.com",
	"log-upload.mihoyo.com",
	"hk4e-sdk.mihoyo.com",
	"api-beta-sdk.mihoyo.com",
	"api-beta-sdk-os.mihoyo.com",
	"cnbeta01dispatch.yuanshen.com",
	"dispatchcnglobal.yuanshen.com",
	"cnbeta02dispatch.yuanshen.com",
	"sdk-os-static.mihoyo.com",
	"webstatic-sea.mihoyo.com",
	"webstatic-sea.hoyoverse.com",
	"hk4e-sdk-os-static.hoyoverse.com",
	"sdk-os-static.hoyoverse.com",
	"api-account-os.hoyoverse.com",
	"hk4e-sdk-os.hoyoverse.com",
	"overseauspider.yuanshen.com",
	"gameapi-account.mihoyo.com",
	"minor-api.mihoyo.com",
	"public-data-api.mihoyo.com",
	"uspider.yuanshen.com",
	"sdk-static.mihoyo.com"
	];
class Handlers {
	static function OnBeforeRequest(oS: Session) {
		for (var i = 0; i < list.length; i++) {
			if (oS.uriContains("https://" + list[i])) {
				oS.host = "127.0.0.1:443"; // This can also be replaced with another IP address.
				break;
			}
		}
	}
};
```

**Comment by 4Benj** [comment]
> for (var i = 0; i < 30; i++) {

can't `list.length` be used here instead of hardcoding the urls to 30 which some people may forget about if they edit the script.

**Comment by memetrollsXD** [comment]
Yeah, but fiddler uses its own weird language so idk if that exists

**Comment by 4Benj** [comment]
I've changed it to `list.length` in my own fiddler so it does work

**Comment by memetrollsXD** [comment]
@lunaticwhat Consider updating the script on readme

**Comment by MlgmXyysd** [comment]
> > for (var i = 0; i < 30; i++) {
> 
> can't list.length be used here instead of hardcoding the urls to 30 which some people may forget about if they edit the script.

No syntax documents were found🤔I wanted to use list.contains

**Comment by 4Benj** [comment]
> > > for (var i = 0; i < 30; i++) {
> > 
> > 
> > can't list.length be used here instead of hardcoding the urls to 30 which some people may forget about if they edit the script.
> 
> No syntax documents were found🤔I wanted to use list.contains

Yeah I tried that as well

**Comment by MlgmXyysd** [comment]
> @lunaticwhat Consider updating the script on readme

No, this may miss some addresses that use the HTTP protocol to connect. In order to bypass connect handshake, I have to process only HTTPS.

**Comment by MlgmXyysd** [comment]
Fiddler is buggy, I still prefer to use mitmproxy instead.

**Comment by 4Benj** [comment]
also you only have to do `if(oS.uriContains(list[i])) {` as it checks if the uri contains the string specified, it doesn't check the full string, so then you don't have to include the `https://` and it will still work for `http://` requests

**Comment by MlgmXyysd** [comment]
> also you only have to do `if(oS.uriContains(list[i])) {` as it checks if the uri contains the string specified, it doesn't check the full string, so then you don't have to include the `https://` and it will still work for `http://` requests

But if HTTPS prefix is not added, Fiddler will make `CONNECT http:// 200 Connect Established` invalid. It's not smart enough.

**Comment by MlgmXyysd** [comment]
https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#complication-1-whats-the-remote-hostname
This is why mitmproxy is better than Fiddler

**Comment by 4Benj** [comment]
> But if HTTPS prefix is not added, Fiddler will make `CONNECT http:// 200 Connect Established` invalid. It's not smart enough.

I swear I had it working a second ago but now fiddler isn't working at all lol

**Comment by naupaw** [comment]
I suggest to open one port only for dispatch, log and login server with config `DispatchServerPort` to other port like `8080` etc... rather than port `80` it also solve problem to run server without root level / administrator.

port 443 for SSL it's optional since your'e playing in local computer, you can use it later when decide to put in public server you can use nginx for handling all https traffic.

And then you can also redirect protocol from https to http using fiddler scripts / mitmproxy example below:

Fiddler
```c++
import System;
import System.Windows.Forms;
import Fiddler;
import System.Text.RegularExpressions;

var list = [
    "https://api-os-takumi.mihoyo.com",
    "https://hk4e-api-os-static.mihoyo.com",
    "https://hk4e-sdk-os.mihoyo.com",
    "https://dispatchosglobal.yuanshen.com",
    "https://osusadispatch.yuanshen.com",
    "https://account.mihoyo.com",
    "https://log-upload-os.mihoyo.com",
    "https://dispatchcntest.yuanshen.com",
    "https://devlog-upload.mihoyo.com",
    "https://webstatic.mihoyo.com",
    "https://log-upload.mihoyo.com",
    "https://hk4e-sdk.mihoyo.com",
    "https://api-beta-sdk.mihoyo.com",
    "https://api-beta-sdk-os.mihoyo.com",
    "https://cnbeta01dispatch.yuanshen.com",
    "https://dispatchcnglobal.yuanshen.com",
    "https://cnbeta02dispatch.yuanshen.com",
    "https://sdk-os-static.mihoyo.com",
    "https://webstatic-sea.mihoyo.com",
    "https://webstatic-sea.hoyoverse.com",
    "https://hk4e-sdk-os-static.hoyoverse.com",
    "https://sdk-os-static.hoyoverse.com",
    "https://api-account-os.hoyoverse.com",
    "https://hk4e-sdk-os.hoyoverse.com",
    "https://osasiadispatch.yuanshen.com",
    "https://abtest-api-data-sg.hoyoverse.com",
    "http://overseauspider.yuanshen.com:8888"
    ];

class Handlers
{
    static function OnBeforeRequest(oS: Session) {
       for(var i = 0; i < list.length; i++) {
            if(oS.uriContains(list[i])) {
                oS.fullUrl = oS.fullUrl.Replace("https://", "http://");
                oS.host = "192.168.1.2";
                oS.port = "8088";
                break;
            }
        }
    }                       
};
```

Mitmproxy
```python
import mitmproxy.http
from mitmproxy import ctx

hosts = [
    "api-os-takumi.mihoyo.com",
    "hk4e-api-os-static.mihoyo.com",
    "hk4e-sdk-os.mihoyo.com",
    "dispatchosglobal.yuanshen.com",
    "osusadispatch.yuanshen.com",
    "account.mihoyo.com",
    "log-upload-os.mihoyo.com",
    "dispatchcntest.yuanshen.com",
    "devlog-upload.mihoyo.com",
    "webstatic.mihoyo.com",
    "log-upload.mihoyo.com",
    "hk4e-sdk.mihoyo.com",
    "api-beta-sdk.mihoyo.com",
    "api-beta-sdk-os.mihoyo.com",
    "cnbeta01dispatch.yuanshen.com",
    "dispatchcnglobal.yuanshen.com",
    "cnbeta02dispatch.yuanshen.com",
    "sdk-os-static.mihoyo.com",
    "webstatic-sea.mihoyo.com",
    "webstatic-sea.hoyoverse.com",
    "hk4e-sdk-os-static.hoyoverse.com",
    "sdk-os-static.hoyoverse.com",
    "api-account-os.hoyoverse.com",
    "hk4e-sdk-os.hoyoverse.com",
    "osasiadispatch.yuanshen.com",
    "abtest-api-data-sg.hoyoverse.com",
    "overseauspider.yuanshen.com",
    "minor-api-os.hoyoverse.com",
    "log-upload-os.hoyoverse.com",
]


class LocalRedirect:

    def __init__(self):
        print('Loaded redirect addon')

    def request(self, flow: mitmproxy.http.HTTPFlow):
        if flow.request.pretty_host in hosts:
            ctx.log.info("pretty host is: %s" % flow.request.pretty_host)
            flow.request.host = "192.168.1.2"
            flow.request.port = 8080
            flow.request.scheme = 'http'


addons = [
    LocalRedirect()
]
```

**Comment by MlgmXyysd** [comment]
> And then you can also redirect protocol from https to http using fiddler scripts / mitmproxy example below:

F, our purpose is not to convert HTTPS to HTTP.

**Comment by MlgmXyysd** [comment]
> I suggest to open one port only for dispatch, log and login server with config `DispatchServerPort` to other port like `8080` etc... rather than port `80` it also solve problem to run server without root level / administrator.
> 
> port 443 for SSL it's optional since your'e playing in local computer, you can use it later when decide to put in public server you can use nginx for handling all https traffic.

In fact, log and dispatch can be started on the same port, which can reduce port occupation. There is no independent login server.

**Comment by MlgmXyysd** [comment]
I guess the current implementation (3 ports) is just a compromise for the proxy

**Comment by naupaw** [comment]
> F, our purpose is not to convert HTTPS to HTTP.

is there any reason ? it's solved problem for people have trouble to install self assign certificate and more technical things. alternative you can serve dispatch server behind nginx when you release on public server.

**Comment by MlgmXyysd** [comment]
> is there any reason ? it's solved problem for people have trouble to install self assign certificate and more technical things.

You should set `UseSSL=false` in both server & proxy config insetad of change to HTTP.

**Pull request closed without merging**
