### PR TITLE
Added a directive to fix some minor bugs

### PR DESCRIPTION
**Pull request by ChisatoNishikigi73**
## Description
1. Generate GM Handbook into a folder
2. Add the "rotation" command to get rotation information (useful for resource writing).
3. Fixed scene ID and number of monsters in "Killall" command
Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
issue#1686

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Birdulon** [comment]
Should just add rotation to `PositionCommand`, there's no situation where you want rotation without position.

**Comment by jie65535** [comment]
> Should just add rotation to `PositionCommand`, there's no situation where you want rotation without position.

Maybe also add scene

**Comment by Birdulon** [comment]
> Maybe also add scene

`PositionCommand` already has scene

**Comment by ChisatoNishikigi73** [comment]
> Should just add rotation to `PositionCommand`, there's no situation where you want rotation without position.

That's good advice. Thank you.

**Review by 2y8e9h22 — COMMENTED** [review]
你把这个顺序调换了，虽然中文变对了。
但其他语言就变成反的了。

**Comment by ChisatoNishikigi73** [comment]
> 你把这个顺序调换了，虽然中文变对了。
> 但其他语言就变成反的了。

我没看过其他语言，我会去看的

**Comment by Birdulon** [comment]
> 你把这个顺序调换了，虽然中文变对了。
> 但其他语言就变成反的了。

Yes, the order is `toKill.size(), scene.getId()` in english.

```json
"kill_monsters_in_scene": "Killing %s monsters in scene %s.",
```

**Comment by ChisatoNishikigi73** [comment]
> > 你把这个顺序调换了，虽然中文变对了。
> > 但其他语言就变成反的了。
> 
> Yes, the order is `toKill.size(), scene.getId()` in english.
> 
> ```json
> "kill_monsters_in_scene": "Killing %s monsters in scene %s.",
> ```

Is only Chinese the opposite? If so, can I add a judgment on Chinese or adjust the order of Chinese language?

**Comment by jie65535** [comment]
> 你把这个顺序调换了，虽然中文变对了。
> 但其他语言就变成反的了。

```patch
    "killall": {
      "scene_not_found_in_player_world": "未在玩家世界中找到此场景。",
-      "kill_monsters_in_scene": "已杀死场景 %s 中的 %s 个怪物。",
+      "kill_monsters_in_scene": "已杀死 %s 个怪物在场景 %s 中。",
      "description": "杀死所有怪物"
    },
```
这个问题可以通过更改中文语序解决，虽然不顺畅，但起码不是错误。
This problem can be solved by changing the word order.

**Comment by ChisatoNishikigi73** [comment]
> 

添加一个针对中文的判定可能会影响到性能，我也决定改变语序

**Pull request closed without merging**
