### PR TITLE
Code Clean Up/Refactor

### PR DESCRIPTION
**Pull request by KingRainbow44**
## Description

An automatic code cleanup by IntelliJ IDEA's "Reformat Code" tool.
Some files might need cherry picking/updating, if this is the case leave a comment on this PR.

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [x] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by KingRainbow44** [comment]
i recommend looking at commits before 
> Automatic refactor by InteliJ IDEA

for actual code changes, then look at that commit and let me know if you agree with the code style.

**Comment by KingRainbow44** [comment]
this is what i get for trying to PR a branch created a month ago
can someone check with my protos on y my build failed lol

**Comment by zhaodice** [comment]
add a function to `PacketEntityFightPropChangeReasonNotify.java` : 

```
public PacketEntityFightPropChangeReasonNotify(GameEntity entity, FightProperty prop, Float value, ChangeEnergyReasonOuterClass.ChangeEnergyReason reason) {
        super(PacketOpcodes.EntityFightPropChangeReasonNotify);

        EntityFightPropChangeReasonNotify proto = EntityFightPropChangeReasonNotify.newBuilder()
            .setEntityId(entity.getId())
            .setPropType(prop.getId())
            .setPropDelta(value)
            .setChangeEnergyReson(reason)
            .build();

        this.setData(proto);
    }
```

**Comment by KingRainbow44** [comment]
Will need to pull latest dev, cherrypick commits, and make another PR.

**Comment by zhd1208** [comment]
运行后插件用不了Enabling plugin: opencommand-pluginException in thread "main" java.lang.NoClassDefFoundError: emu/grasscutter/server/event/game/CommandResponseEvent        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:46)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:136)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:134)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:167)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.server.event.game.CommandResponseEvent        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 more

**Comment by jie65535** [comment]
> 运行后插件用不了Enabling plugin: opencommand-pluginException in thread "main" java.lang.NoClassDefFoundError: emu/grasscutter/server/event/game/CommandResponseEvent at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:46) at  ...

@zhd1208  [OpenCommand Plugin](https://github.com/jie65535/gc-opencommand-plugin/releases) v1.2.2 版本已经支持该更改

_另外，你不应该在此处报告插件的错误。_

---
This change is already supported in [OpenCommand](https://github.com/jie65535/gc-opencommand-plugin/releases) v1.2.2

_Also, you shouldn't report plugin bugs here_

**Pull request closed without merging**
