### PR TITLE
Merge `development` into `stable`

### PR DESCRIPTION
**Pull request by ghost**
(written by @KingRainbow44)
Upgrade to version `1.2.0`!

**Detailed Changelogs**:
- Update READMEs
- Add `lombok` as a dependency
- Add a `BuildConfig.java` file into the JAR containing the artifact details
- Create a generic Grasscutter installer for UNIX systems
- Update `kcp-netty`
- Add a JSON schema for Grasscutter plugins
- Update to anime game `2.7`
- Update `.proto` files to support anime game `2.7`
- Overhaul the configuration system
- Replace the dispatch server with the HTTP server
- Overhaul the authentication system
- Add a requirement for command targets
- Add method for sending a default command's translated messages
- Ensure the player for an account is kicked before deleting the account
- Fix & enhance functionality of commands
- Add a command for changing a specific user's language
- Implement stamina
- Implement quests
- Implement a spawning limit
- Add a command for modifying a player's team(s)
- Implement Spiral Abyss
- Add a command to skip Spiral Abyss floors
- Implement abilities(?)
- Implement crafting
- Implement domains
- Implement gadgets (item gadgets or entity gadgets)
- Implement expeditions
- Implement the character friendship system
- Overhaul the gacha system
- Implement deforestation

*wow actual change logs this time no way*
thanks for the massive support on grasscutter!
currently at: 322 commits with 938 files changed

### CODE REVIEW

**Comment by KingRainbow44** [comment]
see this is where i write the typical version bump changes

**Comment by lunaticwhat** [comment]
no way

**Comment by nitrog0d** [comment]
real

**Comment by KiminaNatsuki** [comment]
oh god oh fuck

**Comment by zhaodice** [comment]
kick ass!

**Pull request merged**
