### PR TITLE
Drowning packets handled

### PR DESCRIPTION
**Pull request by TheLostTree**
Entities that cannot swim(and thus send drownreq packets) will drown and die.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Your [PacketSceneEntityDrownRsp.java](https://github.com/Grasscutters/Grasscutter/pull/151/commits/d64044f9315b408119c638e81fcc57c502aacb93#diff-eff88e81a9d7d5c18e967b8ef7723045a9cf08d82b65cdf82a872da2374d6d80) seems to be missing code.

**Comment by TheLostTree** [comment]
this is truly a git scam moment

**Review by ghost — APPROVED** [review]

**Comment by Mar0xy** [comment]
Why was this merged into stable instead of development?

**Comment by alt3ri** [comment]
wrong branch maybe?

**Comment by ghost** [comment]
My fault, i wasnt checking the branch it was merging to.

**Pull request merged**
