### PR TITLE
[BREAKING CHANGE] proto auto compiled by gradle

### PR DESCRIPTION
**Pull request by WetABQ**
del submodule https://github.com/Grasscutters/Grasscutter-Protos, helps the fast-developing
move all proto files to `./proto/`
the gradle will auto compile all proto files in `./proto/` and generate code in `src/generated/`

fix all the bugs produced in this migration process, I've tested in-game, and it seems no big issues.

### CODE REVIEW

**Comment by Yazawazi** [comment]
👀

**Comment by MlgmXyysd** [comment]
I think SubModule is easier to manage. 👀

**Comment by ghost** [comment]
The reason protos are in a seperate repo is to not have any possible takedown risk on the main repo.

**Comment by memetrollsXD** [comment]
You're welcome to add the generated ones in src/main/java/emu/grasscutter/net/proto

**Comment by WetABQ** [comment]
> You're welcome to add the generated ones in src/main/java/emu/grasscutter/net/proto

it will auto-generate to `emu.grasscutter.net.proto` package

**Comment by WetABQ** [comment]
> The reason protos are in a seperate repo is to not have any possible takedown risk on the main repo.

i will reopen a new separate version, sorry for that

**Pull request closed without merging**
