### PR TITLE
Implement a proper language system

### PR DESCRIPTION
**Pull request by KingRainbow44**
*this PR was* **HELL** *to create.*

Adds a new localization system using `.json` files instead of hardcoding a lot of values in `.java` files.
This allows for us to use a tool like Crowdin! (https://translate.grasscutters.xyz)

**Changelog**:
- Formatting changes
- Switch to using translation keys (ex. `grasscutter.best.server`) instead of file constants
- Load language translation keys from a JSON file in `src/main/resources/languages`

### CODE REVIEW

**Comment by KingRainbow44** [comment]
can I just say thanks to @Melledy for helping create the `en_US.json` file
i did maybe 30 entries, but he did the rest

**Comment by 4Benj** [comment]
> This allows for us to use a tool like Crowdin! (https://translate.grasscutters.xyz/)

😲 There's something on the website! lol
Anyway, I'll review this when I get home

**Comment by maineeeee** [comment]
how do i login back to my genshin priv server i played yesterday but it says cant connect when i try to login back

**Review by ghost — APPROVED** [review]

**Comment by Scirese** [comment]
Will existing translations be preserved?

**Comment by mcxiaoke** [comment]
other existing language files should be translated to the new format

**Comment by ghost** [comment]
Yes, someone will have to migrate the CN ones over before this gets pushed.

**Comment by Scirese** [comment]
> Yes, someone will have to migrate the CN ones over before this gets pushed.

Thanks,That will greatly reduce our work. :)

**Review by 4Benj — APPROVED** [review]

**Review by memetrollsXD — APPROVED** [review]

**Comment by KingRainbow44** [comment]
to the person who initially added the language system, *please don't use constants for languages*

**Pull request merged**
