### PR TITLE
Support record saboteur of server.

### PR DESCRIPTION
**Pull request by nigpo**
Support record saboteur of server that using logback RollingFileAppender, and will show all player who executing command on screen of server.
- [ ] Bug fix
- [ x ] New feature 
- [ ] Enhancement
- [ ] Documentation

### CODE REVIEW

**Comment by zhaodice** [comment]
Recommendation:

```
 static void sendMessage(Player player, String message) {
        if(player == null)
        {
            Grasscutter.getLogger().info("undefined player said :" + message);
        }else{
            player.dropMessage(message);
            CommandResponseEvent event = new CommandResponseEvent(ServerEvent.Type.GAME,player, message);
            event.call();
            Grasscutter.getLogger().info("player "+player+" said :" + message);
        }

    }
```

because player may be null cause `CommandResponseEvent event = new CommandResponseEvent(ServerEvent.Type.GAME,player, message);`  leading to ERROR

**Comment by nigpo** [comment]
> Recommendation:
> 
> ```
>  static void sendMessage(Player player, String message) {
>         if(player == null)
>         {
>             Grasscutter.getLogger().info("undefined player said :" + message);
>         }else{
>             player.dropMessage(message);
>             CommandResponseEvent event = new CommandResponseEvent(ServerEvent.Type.GAME,player, message);
>             event.call();
>             Grasscutter.getLogger().info("player "+player+" said :" + message);
>         }
> 
>     }
> ```
> 
> because player may be null cause `CommandResponseEvent event = new CommandResponseEvent(ServerEvent.Type.GAME,player, message);` leading to ERROR

实际上文字相加里面，只要第一个不为null，后面即使是null的也会变成文字"null"，安卓开发的日志也是这样的

**Comment by exzork** [comment]
You can make simple plugin to do this command logger. Just create an eventlistener by something like this
```
new EventHandler<>(CommandResponseEvent.class).priority(HandlerPriority.HIGH).listener(CommandResponseListener::onSendMessage).register();
```
For  CommandResponseListener :
```
public final class CommandResponseListener {
    public static void onSendMessage(CommandResponseEvent event) {
        if (event.getPlayer() == null) {
            //Server console
        }else{
            //Ingame chat
        }
    }
}

```

**Comment by 4Benj** [comment]
Has this been abandoned?

**Comment by memetrollsXD** [comment]
Closed because of inactivity. Feel free to open another pull request if you feel like you want to resume development for this feature.

**Pull request closed without merging**
