### PR TITLE
add gadget

### PR DESCRIPTION
**Pull request by 66hh**
## Description

Add gadgets to the Handbook

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by 66hh** [comment]
Gadgets in other languages can be translated by naming in the GM version

**Comment by 66hh** [comment]
[mapping-chs.zip](https://github.com/Grasscutters/Grasscutter/files/9099590/mapping-chs.zip)
mapping

**Review by zhaodice — CHANGES_REQUESTED** [review]
路径也被翻译了？“源代码/主要的/爪哇/鸸/割草机/工具/”

**Comment by 66hh** [comment]
> 路径也被翻译了？“源代码/主要的/爪哇/鸸/割草机/工具/”

抱歉，翻译插件的问题，我马上修复一下

**Pull request closed without merging**
