### PR TITLE
add auto spawn entity

### PR DESCRIPTION
**Pull request by WetABQ**
Read entities config from YSLua scene data, and auto spawn those entities.

### CODE REVIEW

**Comment by ghost** [comment]
We cannot include the yslua files because of takedown risk.

**Comment by WetABQ** [comment]
> We cannot include the yslua files because of takedown risk.

could we include yslua just like `BinOutput`?

I do not upload on this pr. i think we could upload those files on another repo, just like `GenshinData`

**Comment by ghost** [comment]
The thing is that the lua files get taken down themselves. See [https://github.com/TheLostTree/YSLua](https://github.com/TheLostTree/YSLua), if you add a link to any lua files, hoyo will find a way to go after them.

**Comment by WetABQ** [comment]
> The thing is that the lua files get taken down themselves. See https://github.com/TheLostTree/YSLua, if you add a link to any lua files, hoyo will find a way to go after them.

Could we add an option to this feature and add those files by users themselves?

If they don't have any YSLua in the resources folder, this feature will auto turn off

**Comment by ghost** [comment]
I'd rather not tell users do go find things that would cause a dmca.

**Comment by Mar0xy** [comment]
I do see the appeal in something like this considering without entities it does feel really empty. and something like this normally should be part of a private server

**Comment by ghost** [comment]
You can do them in other ways without telling users to include luas.

**Comment by WetABQ** [comment]
> You can do them in other ways without telling users to include luas.

It currently doesn't include any Lua, only the json files

**Comment by Colerar** [comment]
The code style of `.kt` is inconsistent with current `.java` files. (For example, `.java` use 2 tab indent, `.kt` use 4 spaces)

We'd better add a `.editorconfig` to make code style uniform.

**Comment by memetrollsXD** [comment]
@Melledy The data itself doesn’t get taken down you say? I’m assuming he only means the JSON files, so that would also be data

**Comment by TheLostTree** [comment]
Personally, i think it's totally fine. Reupload the lua/jsons on a different repo just like the protobufs +  make it disable itself if the folder isnt there.

**Comment by WetABQ** [comment]
> 

im doing serializer for it right now, thanks for suggestion

**Comment by ghost** [comment]
> Personally, i think it's totally fine. Reupload the lua/jsons on a different repo just like the protobufs + make it disable itself if the folder isnt there.

The problem is any sites or repos hosting the luas would receive dmca notices, i think its just safer to parse to json for the time being.

**Comment by ghost** [comment]
@WetABQ Can you merge with to the dev-entity branch instead of development?

**Comment by WetABQ** [comment]
> @WetABQ Can you merge with to the dev-entity branch instead of development?

yes I can

**Comment by WetABQ** [comment]
> > Personally, i think it's totally fine. Reupload the lua/jsons on a different repo just like the protobufs + make it disable itself if the folder isnt there.
> 
> The problem is any sites or repos hosting the luas would receive dmca notices, i think its just safer to parse to json for the time being.

I initially wanted to package all the data into a single JSON just like @Melledy has done in `dev-branch`, but I found that to be too much performance overhead. The current `SceneDataLoader` is implemented via lazy delegation for faster data reading. So I will keep the original JSON file structure.

**Pull request closed without merging**
