### PR TITLE
adding Hebrew version of README.md

### PR DESCRIPTION
**Pull request by Hiro420**
finally hebrew translation of readme!!!

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Hiro420** [comment]
i added hebrew translation :)

**Comment by Hiro420** [comment]
and btw i forgor to add link to this file in the original readme sorry

**Review by ghost — CHANGES_REQUESTED** [review]
Please add links to the hebrew readme in the other readmes.

**Comment by Hiro420** [comment]
i will make it a new pull request

**Pull request closed without merging**
