### PR TITLE
Update(5.0): protocol definitions

### PR DESCRIPTION
**Pull request by HongchengQ**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by KingRainbow44** [comment]
i am so stupid and forgot to update the cmdids file
besides that, what else are you pushing for the definitions? they *should* already be included in unstable...

**Comment by HongchengQ** [comment]
> i am so stupid 和 forgot to update the cmdids file besides that, what else are you pushing for the definitions? they _should_ already be included in unstable...

Many protos are still in an obfuscated state. I have deobfuscated some of these protos and pushed them.

**Comment by KingRainbow44** [comment]
please add your deobfuscated protos to other repos, like yuuki or luna-gc

**Comment by HongchengQ** [comment]
> please add your deobfuscated protos to other repos, like yuuki or luna-gc

https://github.com/HongchengQ/GI_Fatcat_proto.git

**Pull request closed without merging**
