### PR TITLE
Update dev-world-scripts to 2.7

### PR DESCRIPTION
**Pull request by ghost**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My pull request is unique and no other pull requests have been opened for these changes
- [ ] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [ ] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Akka0** [comment]
Is this PR still alive? I have some works need to upload, but wait for it merged. 🥲

**Comment by ghost** [comment]
> Is this PR still alive? I have some works need to upload, but wait for it merged. 🥲

I will merge after dev gets merged into stable (and then test if this can be merged into dev)

**Review by BugzyUA — APPROVED** [review]

**Comment by zhaodice** [comment]
> cant use TOWER there's no room

fixed by #1240

**Comment by KiminaNatsuki** [comment]
Since this is still inactive, I will be posting this fork here since it's dev world scripts too.
https://github.com/Akka0/Grasscutter

**Pull request closed without merging**
