### PR TITLE
Enhance the default permissions logic

### PR DESCRIPTION
**Pull request by omg-xtao**
## Description

Make default permissions not write to the database and be able to alter them dynamically.

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by ghost** [comment]
This change makes more sense but I'd like opinions from other people about this before we merge.

**Comment by jie65535** [comment]
I think many GM need this because the current situation is that it is very troublesome to change the default permissions of old users. For example, a new plug-in has been added with new permissions, which is a nightmare.

**Comment by Birdulon** [comment]
> This change makes more sense but I'd like opinions from other people about this before we merge.

Perhaps it would be useful to go one step further and have permission group aliases so that admins can define permission groups like `user`, `poweruser`, `gm`, and then add whatever permissions their plugins use to those groups as they please.

**Comment by exzork** [comment]
oh god, if this permission is updated it's mean we have to update the database :(

**Comment by omg-xtao** [comment]
> oh god, if this permission is updated it's mean we have to update the database :(

Why? Both new and existing users can have the default permissions.

**Comment by exzork** [comment]
For the default one sure it's, but for custom permission i think no.

**Comment by Birdulon** [comment]
> oh god, if this permission is updated it's mean we have to update the database :(

Under the current system yes, under this PR's system no.

Current system: 
 - User is created, default permissions are added to their account and saved in the db for later.
 - When default permissions are changed, admin has to either:
   - leave old users without these changes, or
   - go through and update all users' individual permissions in the db.

This system:
 - User is created with no attached permissions.
 - Permission checks are performed against not only the individual user, but also against the defaults.
 - When default permissions are changed, they apply to all future permission checks for all users without any db updates.

**Review by ghost — APPROVED** [review]

**Pull request merged**
