### PR TITLE
Implement a plugin system

### PR DESCRIPTION
**Pull request by KingRainbow44**
This will add a system for other developers to add code to the existing Grasscutter codebase.
**Note**: A separate API pull request will have to be made to make adding features easy.

Implements:
- A basic plugin class
- A plugin manager
- An overhauled event system
- Better object logging (for debugging but hey its in this pr!)

### CODE REVIEW

**Comment by KingRainbow44** [comment]
i'll test this in a bit then open for review.
note that a full plugin API for developers will probably come at a later date

**Review by ghost — APPROVED** [review]

**Review by 4Benj — APPROVED** [review]

**Review by memetrollsXD — APPROVED** [review]
Will you write a wiki for plugin devs soon?

**Review by TheLostTree — APPROVED** [review]
Looks great! Definitely will require either a "sample"/"example" plugin or some more documentation of how to use this system.

**Comment by KingRainbow44** [comment]
Developer documentation/an example will be done when I implement an API for wrapping the less friendly methods of Grasscutter.

**Pull request merged**
