### PR TITLE
implement BattlePass (Except missions)

### PR DESCRIPTION
**Pull request by dianwangwin**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

implement BattlePass

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This is a good start, but its missing a lot of battlepass logic.

**Comment by dianwangwin** [comment]
> This is a good start, but its missing a lot of battlepass logic.

Sorry sir 
I don't really know how to fix bp missions due to it should do lots of work in server side

**Comment by GanyusLeftHorn** [comment]
The missions are defined in `BattlePassMissionExcelConfigData`. The info you need to handle them is in `triggerConfig`, which defines various trigger types such as `TRIGGER_LOGIN` (daily login), `TRIGGER_DAILY_TASK` (do your dailies), `TRIGGER_COST_MATERIAL` (use a given material a certain number of times, e.g. resin), `TRIGGER_MONSTER_DIE` (kill the specified monsters a given number of times) etc. You also need `refreshType` to know over which period the triggers have to count.

To actually handle those triggers, you will have to hook into various parts of the backend. For example, you could add a call to `EntityMonster::onDeath` to inform your BP manager that a monster has been killed by the player, so it can update monster kill missions etc.

Not exactly hard to do, but probably a decent bit of work.

**Comment by dianwangwin** [comment]
> The missions are defined in `BattlePassMissionExcelConfigData`. The info you need to handle them is in `triggerConfig`, which defines various trigger types such as `TRIGGER_LOGIN` (daily login), `TRIGGER_DAILY_TASK` (do your dailies), `TRIGGER_COST_MATERIAL` (use a given material a certain number of times, e.g. resin), `TRIGGER_MONSTER_DIE` (kill the specified monsters a given number of times) etc. You also need `refreshType` to know over which period the triggers have to count.
> 
> To actually handle those triggers, you will have to hook into various parts of the backend. For example, you could add a call to `EntityMonster::onDeath` to inform your BP manager that a monster has been killed by the player, so it can update monster kill missions etc.
> 
> Not exactly hard to do, but probably a decent bit of work.

k

**Comment by dianwangwin** [comment]
> 

maybe i will use a event to control it

**Comment by dianwangwin** [comment]
> The missions are defined in `BattlePassMissionExcelConfigData`. The info you need to handle them is in `triggerConfig`, which defines various trigger types such as `TRIGGER_LOGIN` (daily login), `TRIGGER_DAILY_TASK` (do your dailies), `TRIGGER_COST_MATERIAL` (use a given material a certain number of times, e.g. resin), `TRIGGER_MONSTER_DIE` (kill the specified monsters a given number of times) etc. You also need `refreshType` to know over which period the triggers have to count.
> 
> To actually handle those triggers, you will have to hook into various parts of the backend. For example, you could add a call to `EntityMonster::onDeath` to inform your BP manager that a monster has been killed by the player, so it can update monster kill missions etc.
> 
> Not exactly hard to do, but probably a decent bit of work.

 already done for a framework for BP's mission s
but i couldn't fix so much extra work like s3's gargets smh or fix scriptlibs for boos
so how could i do next?

**Comment by ghost** [comment]
I will handle the rest later then, thank you for your contribution.

**Pull request merged**
