### PR TITLE
fix the Monster spawn between stage challenges

### PR DESCRIPTION
**Pull request by Akka0**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
#745
#744
#719

## Type of changes
- fix the Monster spawn between stage challenges

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by 1318354595** [comment]
9楼1号房只有9个守卫

**Comment by 1318354595** [comment]
9楼1号房只有9个守卫

**Comment by 1318354595** [comment]
Room 1 on the 9th floor has only 9 guards

**Comment by daxiwow** [comment]
谢谢你们维护~

**Pull request merged**
