### PR TITLE
3.0 Support (Backrooms Edition) 

### PR DESCRIPTION
**Pull request by 4Benj**
## Description
This pull request brings Grasscutter to 3.0!
I would like to thank all the contributors in the Grasscutter Backrooms for contributing and making this possible.

Change Log:
- Update protos & opcodes
- Fix RegionHandler
- Fix Gadget Spawning
- PointData is now compatible with an "alternative" data
- Added new scene tags
- Added new expeditions
- Update game version
- Added new ReliquaryDecompose and SkillParticleGeneration data
- Removed comments and names from ReliquaryDecompose and SkillParticleGeneration since they are not needed (Requested from @Birdulon)
- Disabled MusicGameSettleReq since the proto has been outdated since 2.8 and was left unnoticed till now....

There are sure to be bugs as we haven't had much activity due to various reasons.

Honourable mentions (everyone else has been co-authored):
@Koko-boya
@Melledy
@Thereallo1026
@alt3ri
@lilmayofuksu
@nitrog0d
@timing1337
@zhaodice
AlienGathering
Cael
Matsko0
Roly
Yarik0chka
ohsyme
zenri
zeroruka

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by alt3ri** [comment]
image

**Comment by GanyusLeftHorn** [comment]
poger

**Comment by jc04-sh** [comment]
Poggers

Poggers

**Comment by TukanDev** [comment]
186189950-f8161862-1c7d-4ff0-ad3d-b052841d3fce

**Comment by zhaodice** [comment]
surprise!

**Review by ghost — APPROVED** [review]

**Comment by lilmayofuksu** [comment]
image

**Comment by AZthemute** [comment]
image
Since the servers are down, I wish you all a good rest. See you all in Sumeru, have a good night if you're sleeping through the maintenance and huge, gigantic and enormous thank you to the Backrooms for making these updates as fluid as possible!

**Comment by ChisatoNishikigi73** [comment]
omg！！！！

**Review by Birdulon — APPROVED** [review]

**Comment by ClickClack7531** [comment]
How to update?

**Pull request merged**
