### PR TITLE
Persist Tower Data && Set The Tower Schedule 

### PR DESCRIPTION
**Pull request by Akka0**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
#661

## Type of changes
- Now tower data can be persisted in the database
- Fix the problem of monster spawn
- Add command unlocktower to unlock all floors of the tower
- Now you can set the schedule of the tower floor

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by tiantian520tt** [comment]
Hello! Thank you for your contribution. However, I found that when I pulled this PR to the local deployment, the problem still could not be solved after compilation. 1-3, 2-3, 4-3 still cannot play, and 3-1 still has an error. Please have a look. Thank you.
(translated from Baidu)

**Comment by Akka0** [comment]
> Hello! Thank you for your contribution. However, I found that when I pulled this PR to the local deployment, the problem still could not be solved after compilation. 1-3, 2-3, 4-3 still cannot play, and 3-1 still has an error. Please have a look. Thank you. (translated from Baidu)

I have tried, and it actually works.

**Comment by tiantian520tt** [comment]
yes. When I restart my server system, it suddenly takes effect. thank you.

**Comment by tiantian520tt** [comment]
fantastic! Everything is running normally. But I want to ask you, dear sir, how to use the unlockpower command? I didn't find the corresponding documentation.

**Comment by tiantian520tt** [comment]
At present, I only found that the progress of killing monsters does not increase on the 8th floor. Others are normal.

**Comment by ghost** [comment]
Can you fix your merge conflicts? Good work otherwise.

**Comment by tiantian520tt** [comment]
I think there will be errors in the merging of upper and lower tasks after level 5, right. Unfortunately, I'm not very good at coding.

**Comment by Akka0** [comment]
> ur merge conflicts? Good work otherwise.

Done.

**Review by ghost — APPROVED** [review]
Oops - ignore this comment.

**Pull request merged**
