### PR TITLE
Set the maximum number of player on the server through the config.json

### PR DESCRIPTION
**Pull request by Coooookies**
## Description
- Set the maximum number of player on the server through the config.json
- Show the maximum number of player on API /status/server
- I18n error message
40 TVLLTCX@KBC}_N({0OYF

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
This isnt going to prevent players with a token already from logging in to the game server.

**Comment by Coooookies** [comment]
> This isnt going to prevent players with a token already from logging in to the game server.

MaxPlayer detection will work in the packet handler (HandlerPlayerLoginReq)

**Comment by nigpo** [comment]
Is there anyway to limit player spawn monsters in world that do not reach the performance as the machine can afford?

**Comment by ghost** [comment]
> Is there anyway to limit player spawn monsters in world that do not reach the performance as the machine can afford?

Will be doing this soon.

**Review by ghost — APPROVED** [review]

**Pull request merged**
