### PR TITLE
Make uid more like an official server

### PR DESCRIPTION
**Pull request by millet6**
让UID更像官方服务器 Make uid more like an official server

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [x] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Birdulon** [comment]
Why do you want automatically generated UIDs to start at `216272600`?

**Comment by millet6** [comment]
> Why do you want automatically generated UIDs to start at `216272600`?

官方服务器UID现在已10位 这只是让它看起来更像，其实没有什么实际意义
The official server uid is now 10 bits, which just makes it look more like it. In fact, it has no practical significance

**Comment by qinastar** [comment]
114514.......

**Comment by millet6** [comment]
> > Why do you want automatically generated UIDs to start at `216272600`?
> 
> 官方服务器UID现在已10位 这只是让它看起来更像，其实没有什么实际意义 The official server uid is now 10 bits, which just makes it look more like it. In fact, it has no practical significance


哦 我说的是中国服务器 UiD

Oh, I'm talking about the Chinese server uid

**Comment by 2y8e9h22** [comment]
别搞笑，快关了

**Comment by eternalcomet** [comment]
可以把开始uid弄成可以通过config.json设置，而不是硬编码。
we can make the start uid been read from config.json

**Comment by 2y8e9h22** [comment]
> 可以把开始uid弄成可以通过config.json设置，而不是硬编码。 we can make the start uid been read from config.json

妮说的对

**Comment by Birdulon** [comment]
> 可以把开始uid弄成可以通过config.json设置，而不是硬编码。
> we can make the start uid been read from config.json

Just edit your database if you want the UID counter to be somewhere silly, you'll need to do it anyway since that is only the initial value.

**Pull request closed without merging**
