### PR TITLE
feat: add ability to buy resin with primogems

### PR DESCRIPTION
**Pull request by hamusuke0323**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by KingRainbow44** [comment]
video showcase please!

**Comment by hamusuke0323** [comment]
> video showcase please!


https://user-images.githubusercontent.com/60880668/230800138-a0568838-27dc-40a6-839a-993712eb7202.mp4

**Review by KingRainbow44 — APPROVED** [review]

**Comment by thecutefinder** [comment]
@hamusuke0323 just wondering, where do the proto files come from? If you made them, why not submit them to the Yuuki proto repo?

**Comment by hamusuke0323** [comment]
> @hamusuke0323 just wondering, where do the proto files come from? If you made them, why not submit them to the Yuuki proto repo?

proto files often come from CloudyPS.

I didn't know I can submit them to it, lmao

**Comment by thecutefinder** [comment]
Yea, Yuuki is on GitLab, you can submit protos there.

**Comment by hamusuke0323** [comment]
> Yea, Yuuki is on GitLab, you can submit protos there.

ok, i understood

**Pull request merged**
