### PR TITLE
Added a force message about grasscutter is free

### PR DESCRIPTION
**Pull request by yingyingyingqwq**
Send a message about grasscutter is free to player when they login the game.

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [X] Enhancement
- [ ] Documentation

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] My pull request is unique and no other pull requests have been opened for these changes
- [X] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [X] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Birdulon** [comment]
They'll just delete it lol

**Comment by yingyingyingqwq** [comment]
I think most of them just clone and compile,it's useful for this kind of people 🤣

**Comment by 4Benj** [comment]
With the coming 2.8 update I don’t think this is completely necessary since most will know what grasscutter is due to them using cultivation for client patching and launching (unless the hosts of the server provides their own patcher/launcher)

**Comment by casksteven** [comment]
They can just revert the commit lol

**Comment by KingRainbow44** [comment]
not only is this pointless, this is also annoying for players.

additionally:


> most will know what grasscutter is due to them using cultivation for client patching and launching

**Pull request closed without merging**
