### PR TITLE
2.8 Support (Backrooms Edition)

### PR DESCRIPTION
**Pull request by 4Benj**
## Description
This pull request brings Grasscutter to 2.8!
The main differences between this one and #1489, is that we've been developing this during the beta and that therefore it contains fixes that the other PR didn't have such as fixing the chat proto and implementing some scene id stuff for the new gaa, additionally that PR required patching the UA, and we patch the metadata instead which can open more (and secure) possibilities. 

Update: Thanks to @Yazawazi, this PR now supports UA patching. However, someone who patched via UA cannot join a server that has ``uaPatchCompatible`` disabled in the config, similarly someone who patched via metadata cannot join a server with ``uaPatchCompatible`` enabled in the config. A UA patched client and a metadata patched client cannot join the same server. Hopefully in the future, will we come up with a solution to connect the two differently patched clients, but for now, this is all we got... 

Additional Feature: Real Passwords!
This allows people to use passwords during login. However, this feature is marked as "experimental" and needs to be enabled in the config because it is currently incompatible with existing accounts for public servers due to the fact that currently, to reset your password you need to request it to be reset it from an administrator.

**This PR will require client patching! To make life easier there is a [draft PR on the Cultivation repo ](https://github.com/Grasscutters/Cultivation/pull/22) which can automatically patch and restore the game's metadata so you can use one client to play on both GC servers and official servers. (However, I recommend you only use Cultivation from now on).**

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
- Chat fixes
- Dispatch key exchange
- Fixes for GAA
among some other things

## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by nitrog0d** [comment]
chat fixes my favorite fix tbh now I can finally see what I say on chat

**Comment by Yazawazi** [comment]
The PR is now compatible with the UA patch client, you can enable the `uaPatchCompatible` option in the configuration. However, it is currently not compatible with the metadata patch and when you enable this option, and this compatibility option does not take into account password login.

Update: From now on, UA Patch players can also log in with their passwords normally!

**Review by MoonLGH — APPROVED** [review]
very real, and most important thing it work

**Review by KingRainbow44 — APPROVED** [review]
code looks good, functionality should be tested by write access

**Comment by 4Benj** [comment]
Alright now this PR is more reasonable lmao. Thanks @Birdulon for the clean up

**Pull request merged**
