### PR TITLE
Fixed can set talent level to 16 bug

### PR DESCRIPTION
**Pull request by jie65535**
Level should be **lower than 16**

### CODE REVIEW

**Comment by alt3ri** [comment]
haven't it corrected already? the way you add the = just make the character talent getting locked

**Comment by memetrollsXD** [comment]
Talent level should be 15 or lower due to client-side restrictions

**Comment by jie65535** [comment]
The problem now is that the talent level can be set to 16, my commit fixed that.
Please review again

**Review by memetrollsXD — APPROVED** [review]

**Comment by Birdulon** [comment]
What happens clientside for a level of 0, or negative numbers?

**Comment by memetrollsXD** [comment]
It also locks the talents I’d imagine

**Comment by alt3ri** [comment]
oops, sorry. Talent lv15 only available in event

**Comment by memetrollsXD** [comment]
Which characters? Max is 15..

**Comment by jie65535** [comment]
# Set talent level to 15
Set talent level to 15

# Set talent level to 16
Set talent level to 16

**Comment by alt3ri** [comment]
that's the reason. I did correct it already. Using >= just make it doesn't right at all

**Pull request merged**
