### PR TITLE
Separating dispatch server and game server

### PR DESCRIPTION
**Pull request by exzork**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

Separating dispatch server and game server. 
Now dispatch server can use only one database ( one account for multiple game server ) and each game server have their own database. 
Dispatch and game server will be communicating using websocket.

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by zhaodice** [comment]
I think dispatch server needn't communicate with game server.
dispatch just need encrypt account information(password and username,uid) with RSA into token,and game server decrypt and verify

**Comment by exzork** [comment]
> I think dispatch server needn't communicate with game server. dispatch just need encrypt account information(password and username,uid) with RSA into token,and game server decrypt and verify

Some of function/method is using account object as their parameter/return so without communicating i don't think it's possible to separate this. Well, you can but it needs to modify that function/method

**Comment by mcxiaoke** [comment]
why websocket, why not just tcp (grpc/thrift)? or http?

**Comment by exzork** [comment]
> why websocket, why not just tcp (grpc/thrift)? or http?

Well, it's just my idea of using websocket. Because we don't need to open new port ( http api is the same tho ).

**Comment by ghost** [comment]
No need to use websockets or anything to bridge the game/dispatch servers together, ideally you should seperate the datastores into an accounts and game datastore which can connect to different mongodb instances if set in the config. The dispatch server would use only the account datastore, and the game server would use both datastores.

**Comment by exzork** [comment]
> No need to use websockets or anything to bridge the game/dispatch servers together, ideally you should seperate the datastores into an accounts and game datastore which can connect to different mongodb instances if set in the config. The dispatch server would use only the account datastore, and the game server would use both datastores.

It's already like that as of grasscutter now right? 
On this pr ( as for i write this comment ) we can set "dispatch key" and the dispatch server will open websocket for the game client to connect to and thus updating available game server ( on game client server selection ). Uid and player counter are handled in dispatch server so no uid conflict will happen.

**Comment by 4Benj** [comment]
> No need to use websockets or anything to bridge the game/dispatch servers together, ideally you should seperate the datastores into an accounts and game datastore which can connect to different mongodb instances if set in the config. The dispatch server would use only the account datastore, and the game server would use both datastores.

In my opinion having two servers interact with the same database is a bad idea and I only did it that way just to get it working when I separated the servers and the web socket approach was something that I had planned on submitting a PR for later but Exzork obviously done it I could.

**Comment by exzork** [comment]
Testing server is on my server, for address you can check it on my discord profile ( ExZork#6937 ). Currently has 2 regions. SG is hybrid with dispatch and USA is game only.

**Comment by exzork** [comment]
I'm planning to rewrite and restructure this shit first before it's ready for review

**Comment by exzork** [comment]
I'll rewrite this using socket io instead of plain websocket

**Pull request closed without merging**
