### PR TITLE
Changing how banners work

### PR DESCRIPTION
**Pull request by nyakakun**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR

Changing how banners work
Creating multiple banners with the same type (gachaType)
Banners in the array are now stored not by banner type (gachaType), but by their own id (scheduleId).
Storing history left the same by types of banners, to combine their history prayers.
Thanks to that the problem with incorrect displaying of banner names was fixed.

Изменение работы баннеров
Создание нескольких баннеров с одинаковым типом (gachaType)
Баннеры в массиве теперь хранятся не по типу баннера (gachaType), а по их собственному ид (scheduleId).
Хранение истории оставил так же по типам баннеров, для объединения их истории молитв.
Благодаря этом была исправлена проблема с некорректным отображением названий баннеров

Изменение ключа массива для баннера с GachaType на ScheduleId, что бы можно было сделать несколько баннеров одного типа.
Изменение входных данных для функции, что бы получать ид баннера
Changing the array key for a banner from GachaType to ScheduleId, so you can make multiple banners of the same type.
Changing the input data for the function to get the ID of the banner.
[src/main/java/emu/grasscutter/game/gacha/GachaManager.java](https://github.com/Grasscutters/Grasscutter/compare/dev-world-scripts...nyakakun:dev-world-scripts?expand=1#diff-e39f98e4317984eaedf9bf08452018746eb802f8c3dfc549916d447a316badce)

Изменение ссылки, которая отправляется клиенту игры, на данные баннера
Changing the link that is sent to the client of the game to the banner data
[src/main/java/emu/grasscutter/game/gacha/GachaBanner.java](https://github.com/Grasscutters/Grasscutter/compare/dev-world-scripts...nyakakun:dev-world-scripts?expand=1#diff-e9fe748a6bda3ed98818a8363dd2521f497d94639ff0ee80a0e44442dcb87dca)

Изменение передаваемых данных, когда игрок молится, с типа баннера на его ид.
Changing the data transmitted when a player prays, from banner type to his id.
[src/main/java/emu/grasscutter/server/packet/recv/HandlerDoGachaReq.java](https://github.com/Grasscutters/Grasscutter/compare/dev-world-scripts...nyakakun:dev-world-scripts?expand=1#diff-4ba55d48007abf901cc3e05764d806eece5a7ad35cdeb1c7749e425e02b436ea)

Изменение получения данных при запросе клиентом информации о баннере
Changing the data retrieval when the client requests information about the banner
[src/main/java/emu/grasscutter/server/http/handlers/GachaHandler.java](https://github.com/Grasscutters/Grasscutter/compare/dev-world-scripts...nyakakun:dev-world-scripts?expand=1#diff-f9c556a2f4e3959bbcdbd941e501308d3b0da1346e5f588720445e58576bdbba)

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
This should be targeted at the development branch.

**Comment by Birdulon** [comment]
Seems like it works (cherry-picked to `development` locally) but it seems like `beginTime` isn't being respected by the client so it shows banners that are scheduled to start after the current ones, alongside the current ones. (they can also be pulled on)

image
image

Records seem to be correctly shared at least.

**Comment by Birdulon** [comment]
As far as I can tell this seems reasonable, will approve when it's rebased and retargeted to `development`.

Maybe we should add some code later to prevent sending banners which haven't started yet to the client.

**Comment by nyakakun** [comment]
OK, I'll redo it all under the development branch and resend it

**Pull request closed without merging**
