### PR TITLE
Add new function: Httpapi

### PR DESCRIPTION
**Pull request by Searchstars**
## Description

Added HttpApi, now users can send a post request to `/api/do_command` to execute commands in the console, the content of the post request is the command content, and all command-related output will be returned and output in the console
Added HttpApi part in Config, including Useapi, UseApiKey and ApiKey. By setting HttpApi to true or false, you can control the on/off of HttpApi function, and by setting HttpApi to true or false, you can control whether to enable HttpApiKey (That is, do you need a key when using HttpApi), changing the ApiKey can modify the key provided when using HttpApi to ensure security.

Example of use (config.httpapi.UseApiKey == "false"):

image

Example of use (config.httpapi.UseApiKey == "true" and config.httpapi.ApiKey="Grasscutter123"):

image

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by ghost** [comment]
This kind of stuff may be better off in a plugin.

**Comment by Searchstars** [comment]
> This kind of stuff may be better off in a plugin.

I understand, but I think this functionality should be provided by Grasscutter itself rather than a plugin. This function can greatly improve the efficiency of users. Imagine that you deploy Grasscutter on a **cloud server**, but suddenly you need to execute an instruction to ban a player. At this time, you can use the script you have prepared or use this The program developed by the api directly executes commands without entering the game or logging in to the cloud server

**Comment by zxl-qq927489674** [comment]
好耶

**Comment by Roly-lol** [comment]
In this case, even if automatic registration is turned off, players with permissions can use account create to register new accounts in the game.

**Comment by 4Benj** [comment]
> Imagine that you deploy Grasscutter on a cloud server

yes but not everyone would be doing that and this can be considered as unnecessarily bloat.
You can very easily put this into a plugin which people can install if they need it. iirc people have already done this.

**Comment by KingRainbow44** [comment]
based on feedback presented above, i will be closing this issue.
feel free to make this into a plugin however.

**Pull request closed without merging**
