### PR TITLE
Added admin commands, refactored help command, and created command descriptions + more

### PR DESCRIPTION
**Pull request by 4Benj**
Changes:
- Added default to usage() for command annotations
- Added descriptions to commands
- Added `account.hasPermission(permission)` instead of using `!permissions.contains("*") && !permissions.contains(permissionNode)` and changed the usage in CommandMap
- Added a wip kick command. at the moment it just closes the session which just freaks out the server because the client tries to connect like 10 times before it gives up and reconnects (This is more of a placeholder thing until we can actually disconnect players and send like a server message or something)
- Added a stop command which just kills the server and notifies the players
- Added a broadcast command which messages all players
- Reimplemented my sendmsg command but made it sendservermessage (sendmsg as a player sends a direct message from the sent player... I think, I haven't had another device to test it on)
- Changed reload command so there is feedback when sending as player
- Refactored help command to make it look better, display it's description, and not display the same command multiple times because of aliases
- Removed "usage: " from all usages 

Screenshot of help command is console:
image

Screenshot of help command in-game:
`/help`
image
`/help sendmessage`
image

### CODE REVIEW

**Comment by alt3ri** [comment]
<3

**Comment by SpikeHD** [comment]
Just as a heads up since they were *just* added, this is gonna have residual `Usage: XYZ` strings for the usages of `setworldlevel` and `givechar` :)

**Comment by 4Benj** [comment]
Didn't realise that was merged, sorry. I'll make the same changes to those commands as I did with the others

**Comment by 4Benj** [comment]
> How to solve the relic entry
I'm not sure, go ask on the [discord](https://discord.gg/T5vZU6UyeG) and please keep PR comments about the PR

**Comment by 4Benj** [comment]
Just a heads up in case this gets pushed in.
This is the error that spams the console due to the client trying to keep it's connection alive when it's been closed.
Probably should go into a known-issues part of the readme or something (along with the relic thing) until we find a way to actually kick players from the game server.
This also happens when you quickly stop and start the server (even without the `/stop` command and the client isn't given enough time to timeout.
```
[INFO] Client disconnected from 127.0.0.1
[INFO] Client connected from 127.0.0.1
io.jpower.kcp.netty.KcpException: State=-1 after update()
        at io.jpower.kcp.netty.UkcpServerChannel.run(UkcpServerChannel.java:395)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by MlgmXyysd** [comment]
> Just a heads up in case this gets pushed in. This is the error that spams the console due to the client trying to keep it's connection alive when it's been closed by the server. Probably should go into a known-issues part of the readme or something (along with the relic thing) until we find a way to actually kick players from the game server. This also happens when you quickly stop and start the server (even without the `/stop` command) and the client isn't given enough time to timeout.
> 
> ```
> [INFO] Client disconnected from 127.0.0.1
> [INFO] Client connected from 127.0.0.1
> io.jpower.kcp.netty.KcpException: State=-1 after update()
>         at io.jpower.kcp.netty.UkcpServerChannel.run(UkcpServerChannel.java:395)
>         at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
>         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.lang.Thread.run(Unknown Source)
> ```

The same error here, but not shutting down the server. This error also occurs when the client exits abnormally.

**Review by KingRainbow44 — APPROVED** [review]

**Pull request merged**
