### PR TITLE
Update gradle, Implemented live gacha reloading, and game server event buses

### PR DESCRIPTION
**Pull request by 4Benj**
Exactly what the title says basically. 
Oh also /reload can also reload banners.json and live gacha watching is disabled by default in config.

Also if anyone questions the really long commit name (ba56ccf) blame Solael#8462 on discord

### CODE REVIEW

**Comment by 4Benj** [comment]
DO NOT MERGE I DID A BAD THING

**Comment by 4Benj** [comment]
Fixed lol

**Review by KingRainbow44 — APPROVED** [review]
just a note: ill be overhauling your existing event system when i start developing the plugin API, thanks for the base tho

**Comment by 4Benj** [comment]
> just a note: ill be overhauling your existing event system when i start developing the plugin API, thanks for the base tho

Yeah it's already shit, I just thought it would be useful to have something there for now. I was learning event buses in java when coding it and can see many potential errors

**Pull request merged**
