### PR TITLE
Try to implement NpcTalk packets

### PR DESCRIPTION
**Pull request by w4123**
Currently, the client will pause for a long time after talking to an NPC. This is because the NpcTalk* packets are not implemented.
This PR tries to implement these packets, only a stub packet is included for now but at least it removes the long pause.

Work in Progress to ensure correctness and completeness.

### CODE REVIEW

**Comment by w4123** [comment]
Didn't find any information about which item to give after a conversation with rewards... does anyone has any idea?

**Comment by memetrollsXD** [comment]
You need to do that server-side with the NPC id, and then add that to a list saved in the database, so you can send MetNpcListNotify at startup

**Comment by lunaticwhat** [comment]
a weird information: If during the hang after talking to NPCs, by reconnecting to the server made the client can continue after that hang with dialogues or anything that a normally the game would work.

**Comment by w4123** [comment]
> You need to do that server-side with the NPC id, and then add that to a list saved in the database, so you can send MetNpcListNotify at startup

I tried to play with the MetNpcListNotify packet but it seems that it is not really related to talking to Npcs.  MetNpcListNotify, MeetNpcReq and MeetNpcRsp are used to determine and record whether an Npc has been met before. I tried to set it on random Npcs but it yield no effect. According to NpcFirstMetExcelConfigData.json, I suspect that the field is only used for a very small proportion of Npcs but not all.

Therefore, the problem of giving items to the player after they complete the dialogue with rewards remains unsolved. I think maybe a stub that prevents the hang of the client when talking to the Npcs would be sufficient for the moment. I will investigate deeper and try to implement the complete feature in another PR or something.

**Comment by memetrollsXD** [comment]
MeetNpc is used for NPCs that give rewards, so it doesn't give them twice

**Comment by w4123** [comment]
> 

There is no MeetNpcReq packet sent from the client when I complete the dialogue with an NPC that gives rewards...
Meanwhile, I don't know which item to give anyway.

**Comment by ghost** [comment]
@w4123 Could you make a pull with the protos you added into [https://github.com/Grasscutters/Grasscutter-Protos](https://github.com/Grasscutters/Grasscutter-Protos)? Thanks!

**Comment by w4123** [comment]
> @w4123 Could you make a pull with the protos you added into https://github.com/Grasscutters/Grasscutter-Protos? Thanks!

https://github.com/Grasscutters/Grasscutter-Protos/pull/1

**Pull request merged**
