### PR TITLE
修复 空指针 Fix null pointer

### PR DESCRIPTION
**Pull request by millet6**
## Description

修复 空指针 Fix null pointer

## Issues fixed by this PR
QQ截图20220815011331

让它得到魔拉 Let it get gold coins

## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by eternalcomet** [comment]
a pr is making big changes on chest reward system.see #1379 ,so it's not recommended to make changes on ChestReward.json.however,this pr #1379   hasn't been updated for a,long time.

#1379 正在对宝箱奖励机制做出较大的调整，不建议在他合并之前去改ChestReward.json。

**Comment by eternalcomet** [comment]
Besides,your pr is,only a relief measure,not solving the elemental problem.it is supposed to reward BGM(旋曜玉帛),rather than mora.

而且你这个只是权宜之计，拾取这个应该给旋曜玉帛而不是摩拉

**Comment by eternalcomet** [comment]
i'm busy these days,but i want to spare some time to do the loot table,improving pr #1379 do you have some good idea or suggestion? @Birdulon @Melledy @zhaodice

**Comment by millet6** [comment]
> 

旋曜玉帛 目前版本没有实际意义，因为家园不可用 The current version of Xuanyao jade and silk has no practical significance because the home is unavailable

**Comment by eternalcomet** [comment]
在我印象里当前版本尘歌壶是好使的啊，虽然有bug但还是能进去的。

As far as i know,the teapod of current version is available,despite some bugs.

**Comment by Birdulon** [comment]
> Besides,your pr is,only a relief measure,not solving the elemental problem.it is supposed to reward BGM(旋曜玉帛),rather than mora.

^^^

We would prefer not to treat symptoms by making the underlying cause worse. Someone else would just open an issue about how the reward was wrong anyway.

**Pull request closed without merging**
