### PR TITLE
Add command to get reliquary with specific props

### PR DESCRIPTION
**Pull request by Secack**
Usage: `giveart|givea [player] <artifactId> <mainPropId> [<appendPropId>[,<times>]]... [level]`

Examples: 
`/giveart 23414 50980 965002 965004 965007 965009`

`/giveart 77524 50990 965002 965004,10 965007,10 965009 21`
> `965004,10` means `965004` repeats `10` times

mainPropId can get from [ReliquaryMainPropExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/master/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json)
appendPropId can get from [ReliquaryAffixExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/master/ExcelBinOutput/ReliquaryAffixExcelConfigData.json)

### CODE REVIEW

**Comment by alt3ri** [comment]
Finally, I can abandon my /giveart

**Review by memetrollsXD — CHANGES_REQUESTED** [review]
1. Please command to documentation

2. Wouldn't it be easier for you to use this syntax?: `giver <relicId> <mainStatId> [substatIds] [level] [player]`

**Comment by QiE2035** [comment]
I think the appendPropId maybe need to use an array format. Then we can custom the appendPropId. Because not all have 9 appendProp.

example: `/giver 23414 [50980,965002,965002,965004,965004,965007 965007,965009,965009] 21`
(or don't have the '[]' ?

**Comment by 1shin-7** [comment]
can you rename the `relic` to `artifact`?~~calling artifacts relic is very strange and a little bit.... inauspicious~~

**Comment by Secack** [comment]
> can you rename the `relic` to `artifact`?~calling artifacts relic is very strange and a little bit.... inauspicious~

OK😂

**Comment by Secack** [comment]
> 1. Please command to documentation
> 2. Wouldn't it be easier for you to use this syntax?: `giver <relicId> <mainStatId> [substatIds] [level] [player]`

I have added it. Please review changes

**Review by memetrollsXD — APPROVED** [review]

**Pull request merged**
