### PR TITLE
add drops for animals wild pig,fishes,foxes,birds

### PR DESCRIPTION
**Pull request by zhaodice**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
#1071

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Birdulon** [comment]
>+1 −199,808

Huh?

**Comment by zhaodice** [comment]
> > +1 −199,808
> 
> Huh?

oh, I forgot format json

**Comment by GanyusLeftHorn** [comment]
1.) Please retarget this to the `development` branch.
2.) Why did you remove all whitespace from `Drop.json`?

**Comment by zhaodice** [comment]
> whitespace

I will re-commit it, cause by editor automatically removing

**Pull request closed without merging**
