### PR TITLE
Improve KCP Library

### PR DESCRIPTION
**Pull request by zhaodice**
## Description
Improve(Refactor) KCP Library

## Issues fixed by this PR

https://github.com/Grasscutters/Grasscutter/issues/1023

## Type of changes

- [ ] Bug fix
- [ ] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by ghost** [comment]
Please do not put entire libraries directly into our codebase.

**Comment by zhaodice** [comment]
> Please do not put entire libraries directly into our codebase.

oh, I see , I will re-create this request when my another pull request merged

**Comment by zhaodice** [comment]
> Please do not put entire libraries directly into our codebase.

oh, I see , I will re-create this request when my another pull request merged

**Comment by BiosNod** [comment]
I suppose this will be a very funny time waste to rewrite a whole library in a different way for the sake of following the testaments of Melledy, think about it well _w_

**Pull request closed without merging**
