### PR TITLE
Fix no static gadget in the map,example: no tree but a fruit in the air

### PR DESCRIPTION
**Pull request by zhaodice**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [ ] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by xNissX233** [comment]
I still have the bug. Server updated with latest commit.
Screenshot_20220701_215806
Screenshot_20220701_220107
Screenshot_20220701_220125

**Comment by GanyusLeftHorn** [comment]
Have you deleted your `data/GadgetSpawns.json` so it gets updated on restart of the server?

**Comment by xNissX233** [comment]
> Have you deleted your `data/GadgetSpawns.json` so it gets updated on restart of the server?

I didn't. Now after deleting it, I see that it's solved, but only with scripting disabled (I suppose that's normal?).

**Comment by zhaodice** [comment]
> > Have you deleted your `data/GadgetSpawns.json` so it gets updated on restart of the server?
> 
> I didn't. Now after deleting it, I see that it's solved, but only with scripting disabled (I suppose that's normal?).

this pr is conflicted to script (duplicate spawn some gadget from script)

**Pull request merged**
