### PR TITLE
Rewrite commands

### PR DESCRIPTION
**Pull request by MlgmXyysd**
* Inspired by CraftBukkit, we can easily use `sender == null` in the method to determine whether the command sender is a player.
* Drop `java.lang.Void execute(emu.grasscutter.game.GenshinPlayer, java.util.List<java.lang.Strings>)` & `java.lang.Void execute(java.util.List<java.lang.Strings>)` method, now they are merged into one `java.lang.Void onCommand(emu.grasscutter.game.GenshinPlayer, java.util.List<java.lang.Strings>)`.
* Drop `Execution` enum.
* Drop `execution` in `Command` annotation.
* Split commands into different classes.
* Rewrite a large number of commands.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by 4Benj** [comment]
~~I know you were working on this when the commands were added but this is missing the new commands added by @alt3ri~~
Ignore me I didn't realise this was going to go into stable

**Comment by MlgmXyysd** [comment]
> This is missing the new commands added by @alt3ri

🤔my base is bde8a2114083e3ff312ca09e8bd21d2c543d3ea3

**Comment by 4Benj** [comment]
Yeah I didn't realise that sorry

**Comment by ghost** [comment]
Oh i forgot to mention, but you need to be targeting the dev branch, not stable

**Comment by MlgmXyysd** [comment]
hmmm I think it will be a big conflict

**Comment by MlgmXyysd** [comment]
There should be no rewrite omission.
@4Benj check it

**Comment by 4Benj** [comment]
I shall check now

**Comment by 4Benj** [comment]
Everything seems fine, honestly I didn't check what the commands do I just checked if everything was there.
There was a second sendmessage command which I believe private messaged another player if a player used it.
I don't think it's needed honestly but idk maybe ask @KingRainbow44 as he implemented it.

**Review by KingRainbow44 — APPROVED** [review]

**Comment by KingRainbow44** [comment]
the only issue is github is being stupid af rn and wont let me auto merge files

**Pull request merged**
