### PR TITLE
Add maximum level/refinement/rank to clear command

### LINKED ISSUE #1473: Command "\clear art" is useless. [Bug]
"\clear wp" is usefull, but "\clear art" is useless for command generated items. The command "\clear all" can not delete the "arts" also.

### PR DESCRIPTION
**Pull request by Birdulon**
## Description

Adds `[lv<max level>] [r<max refinement>] [<max rarity>*]` arguments to `clear` command, which allows finer control over deleting trash, as well as the previously missing ability to delete high level artifacts.

Defaults to level 1, refinement 1, 4* which should be somewhat similar to the previous use case. Artifact levels are treated as 0-20 instead of 1-21, as in current `give` command.

## Issues fixed by this PR
Resolves #1473

## Type of changes

- [ ] Bug fix
- [x] New feature 
- [x] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by WK-ice** [comment]
I have tested this code, but unfortunately it doesn't work on my computer, and it cause another bug--After I enter "/clear all", the characters cannot use their weapons, only "E" and "Q" can be correctly triggered. I am hopefully waiting your further correction, thank you!

**Comment by WK-ice** [comment]
I have tested this, it is useful, thank you!

**Comment by Birdulon** [comment]
> I have tested this, it is useful, thank you!

Was the error you encountered before unrelated? I can do some more testing later today

**Comment by WK-ice** [comment]
The problem I encountered yesterday does not appear today, thus I guess it is an&nbsp;accidental problem might be caused by my personal environment. I execute the command "/clear art lv90 5*" and it leads to the desired result.&nbsp;


Thank you for the concern on my question! Have a nice day!

**Review by WK-ice — APPROVED** [review]
I have tested this code, and it indeed solves the problem. Great!

**Review by WK-ice — APPROVED** [review]

**Review by WK-ice — APPROVED** [review]

**Review by memetrollsXD — APPROVED** [review]

**Pull request merged**
