### PR TITLE
Permission Manager

### PR DESCRIPTION
**Pull request by dianwangwin**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes
Implemented a simple permission manager, while the implementation of Ban Command /
Future can include device blocking or ip blocking in the check
Permissions can be restricted for some actions

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by 4Benj** [comment]
Before you read please note that I haven’t look too far into the code

The ban system is useful but what is the point of having both a permissionLevel and a permissionNode system?

**Comment by dianwangwin** [comment]
Because most people won't want to enter that much permission node to get people to get some basic permissions

**Comment by 4Benj** [comment]
Additionally I think permission groups should be separated into a seperate plugin to not over-complicate a vanilla server also I believe the your implementation of permission groups offers little customisation.

**Comment by dianwangwin** [comment]
So do I need to continue with the custom development or just stop developing in this area

**Comment by 4Benj** [comment]
> Because most people won't want to enter that much permission node to get people to get some basic permissions

If it is a serious server then they would, they would want to customise the permissions given to their users as much as they want. If they just want to give them basic permissions because they are lazy, they’d just give them player.* or something like that

**Comment by 4Benj** [comment]
> So do I need to continue with the custom development or just stop developing in this area

I would recommend converting your permissionGroup system into a plugin, base it off of the existing permission node system and allow it to be editable via json files. However, a pull request may have to be submitted for permissions to be handed out to a class with a “PermissionHandler” interface (with a DefaultPermissionHandler within the pull request which would basically just be the existing system but separated into a seperate class).

**Pull request closed without merging**
