### PR TITLE
feat: change game time

### PR DESCRIPTION
**Pull request by hamusuke0323**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by KingRainbow44** [comment]
since the proto is *sorta?* known, can you deobfuscate the name?

**Comment by hamusuke0323** [comment]
> since the proto is _sorta?_ known, can you deobfuscate the name?

proto:https://github.com/CloudyPS/protos
ok, i will deobfuscate it.

**Review by KingRainbow44 — APPROVED** [review]
please send a video of it working!

**Comment by hamusuke0323** [comment]
> please send a video of it working!

yea. i will take video, pls wait

**Comment by hamusuke0323** [comment]
> please send a video of it working!


https://user-images.githubusercontent.com/60880668/220497039-2e1a79b6-076a-4067-9623-32df7a5159ed.mp4

**Comment by KingRainbow44** [comment]
lets just pray it works in coop lmao

**Pull request merged**
