### PR TITLE
Implement the Home System (Serenitea Pot)

### PR DESCRIPTION
**Pull request by Akka0**
## Description

Implement the Home System (Serenitea Pot)

- [x] Support players to open the home world edit mode and save their arrangement
  - [x] Persist the home arrangement into DB
  - [x] Load default home arrangement save from bin output
  - [x] Implement the MapMark of the home world (only support the teleport point)
  - [x] Support NPC/Animals spawn
  - [x] Enter the room scene
  - [x] Furniture Suite
- [x] Support furniture items in ItemData
  - [x] home coin (204) and pay in the shop
  - [x] furniture unlock and make
- [x] Update morphia to 2.2.7 and fix the persistence of the list

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [ ] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by RealHeart** [comment]
cool!

**Comment by qizai3** [comment]
大佬牛

**Comment by qinastar** [comment]
dalao

**Comment by cxfm666** [comment]
java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because the return value of "emu.grasscutter.game.player.Player.getRealmList()" is null
        at emu.grasscutter.server.packet.send.PacketHomeMarkPointNotify.<init>(PacketHomeMarkPointNotify.java:20)
        at emu.grasscutter.game.home.GameHome.onOwnerLogin(GameHome.java:68)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1341)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:233)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Akka0** [comment]
> java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because the return value of "emu.grasscutter.game.player.Player.getRealmList()" is null
> at emu.grasscutter.server.packet.send.PacketHomeMarkPointNotify.(PacketHomeMarkPointNotify.java:20)
> at emu.grasscutter.game.home.GameHome.onOwnerLogin(GameHome.java:68)
> at emu.grasscutter.game.player.Player.onLogin(Player.java:1341)
> at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
> at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
> at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:233)
> at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
> at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
> at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> at java.base/java.lang.Thread.run(Thread.java:833)

I have fixed it.

**Comment by cissy0912** [comment]
大佬万岁~

**Comment by 66hh** [comment]
It is recommended to add the building import / export function so that players can share their own buildings

**Comment by qingchunnh** [comment]
> 建议增加建筑导入/导出功能，让玩家可以共享自己的建筑

保存到数据库里那么玩家分享自己的数据库你导入了不就可以？

**Comment by zhd1208** [comment]
大佬为什么我进壶里只有一个小精灵在半空中，没有房子，然后我想点小精灵对话就会报错
java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.deployAnimalList" is null
        at emu.grasscutter.game.home.HomeBlockItem.toProto(HomeBlockItem.java:55)
        at emu.grasscutter.game.home.HomeSceneItem.lambda$toProto$1(HomeSceneItem.java:76)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at emu.grasscutter.game.home.HomeSceneItem.toProto(HomeSceneItem.java:76)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)

**Comment by Akka0** [comment]
> 大佬为什么我进壶里只有一个小精灵在半空中，没有房子，然后我想点小精灵对话就会报错
> java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.deployAnimalList" is null
> at emu.grasscutter.game.home.HomeBlockItem.toProto(HomeBlockItem.java:55)
> at emu.grasscutter.game.home.HomeSceneItem.lambda$toProto$1(HomeSceneItem.java:76)
> at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
> at emu.grasscutter.game.home.HomeSceneItem.toProto(HomeSceneItem.java:76)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)

Clear the homes database.

**Comment by tonylai000** [comment]
您好，壶内的摆放按键没反应，报错如下，是那一部分出的问题呢？我尝试把改动放进了您的大世界分支。
> java.lang.NullPointerException
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at emu.grasscutter.server.packet.send.PacketHomeGetArrangementInfoRsp.<init>(PacketHomeGetArrangementInfoRsp.java:21)
        at emu.grasscutter.server.packet.recv.HandlerHomeGetArrangementInfoReq.handle(HandlerHomeGetArrangementInfoReq.java:17)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:277)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:608)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Akka0** [comment]
> 您好，壶内的摆放按键没反应，报错如下，是那一部分出的问题呢？我尝试把改动放进了您的大世界分支。
> 
> > java.lang.NullPointerException
> > at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> > at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> > at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> > at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> > at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> > at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> > at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> > at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> > at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> > at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> > at emu.grasscutter.server.packet.send.PacketHomeGetArrangementInfoRsp.(PacketHomeGetArrangementInfoRsp.java:21)
> > at emu.grasscutter.server.packet.recv.HandlerHomeGetArrangementInfoReq.handle(HandlerHomeGetArrangementInfoReq.java:17)
> > at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
> > at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:277)
> > at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> > at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> > at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> > at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> > at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> > at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:608)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
> > at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
> > at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
> > at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
> > at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> > at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> > at java.base/java.lang.Thread.run(Thread.java:833)

Clear the homes database

**Comment by wl23333** [comment]
Placed animals do not show
E4O0B YLG%SFU}33J9}M_KS
LGX{ 3{U_J5MCD02SMONHX8

**Comment by zhd1208** [comment]
进入壶，会卡在进度条最后四分之一格子那里，然后一直处在加载页面等掉线后也会处于加载界面进不了大世界，只能在控制台传送走。java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.persistentFurnitureList" is null
        at emu.grasscutter.game.home.HomeBlockItem.toProto(HomeBlockItem.java:61)
        at emu.grasscutter.game.home.HomeSceneItem.lambda$toProto$1(HomeSceneItem.java:77)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at emu.grasscutter.game.home.HomeSceneItem.toProto(HomeSceneItem.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at emu.grasscutter.server.packet.send.PacketHomeGetArrangementInfoRsp.<init>(PacketHomeGetArrangementInfoRsp.java:21)
        at emu.grasscutter.server.packet.recv.HandlerHomeGetArrangementInfoReq.handle(HandlerHomeGetArrangementInfoReq.java:17)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhd1208** [comment]
进入壶，会卡在进度条最后四分之一格子那里，然后一直处在加载页面等掉线后也会处于加载界面进不了大世界，只能在控制台传送走。java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.persistentFurnitureList" is null
        at emu.grasscutter.game.home.HomeBlockItem.toProto(HomeBlockItem.java:61)
        at emu.grasscutter.game.home.HomeSceneItem.lambda$toProto$1(HomeSceneItem.java:77)
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
        at emu.grasscutter.game.home.HomeSceneItem.toProto(HomeSceneItem.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at emu.grasscutter.server.packet.send.PacketHomeGetArrangementInfoRsp.<init>(PacketHomeGetArrangementInfoRsp.java:21)
        at emu.grasscutter.server.packet.recv.HandlerHomeGetArrangementInfoReq.handle(HandlerHomeGetArrangementInfoReq.java:17)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Review by ghost — APPROVED** [review]

**Comment by Akka0** [comment]
> 进入壶，会卡在进度条最后四分之一格子那里，然后一直处在加载页面等掉线后也会处于加载界面进不了大世界，只能在控制台传送走。java.lang.NullPointerException: Cannot invoke "java.util.List.forEach(java.util.function.Consumer)" because "this.persistentFurnitureList" is null
> at emu.grasscutter.game.home.HomeBlockItem.toProto(HomeBlockItem.java:61)
> at emu.grasscutter.game.home.HomeSceneItem.lambda$toProto$1(HomeSceneItem.java:77)
> at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
> at emu.grasscutter.game.home.HomeSceneItem.toProto(HomeSceneItem.java:77)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
> at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
> at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
> at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
> at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
> at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
> at emu.grasscutter.server.packet.send.PacketHomeGetArrangementInfoRsp.(PacketHomeGetArrangementInfoRsp.java:21)
> at emu.grasscutter.server.packet.recv.HandlerHomeGetArrangementInfoReq.handle(HandlerHomeGetArrangementInfoReq.java:17)
> at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
> at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
> at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
> at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
> at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
> at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> at java.base/java.lang.Thread.run(Thread.java:833)

Clear the home database.

**Comment by mxtilx** [comment]
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 22
^/Dashboard/DK-.-:25z{G7)[_L9T^h+}_8-Amr-}_-j/_$(q_4WkS43%4HS7o&/?$
                      ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3309)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2214)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at kotlin.text.Regex.<init>(Regex.kt:89)
        at io.javalin.core.PathParser.<init>(PathParser.kt:27)
        at io.javalin.websocket.WsEntry.<init>(WsPathMatcher.kt:14)
        at io.javalin.websocket.JavalinWsServlet.addHandler(JavalinWsServlet.kt:79)
        at io.javalin.Javalin.addWsHandler(Javalin.java:551)
        at io.javalin.Javalin.ws(Javalin.java:580)
        at io.javalin.Javalin.ws(Javalin.java:569)
        at top.cyqi.websocket.WebSocketServer.start(WebSocketServer.java:98)
        at top.cyqi.GrasscuttersWebDashboard.onEnable(GrasscuttersWebDashboard.java:95)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:131)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:129)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:159)

**Comment by Birdulon** [comment]
>at top.cyqi.GrasscuttersWebDashboard.onEnable(GrasscuttersWebDashboard.java:95)

This exception has nothing to do with this pull request, this is not an appropriate place to ask for generic support or unrelated plugin support.

**Comment by mxtilx** [comment]
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 22
^/Dashboard/DK-.-:25z{G7)[_L9T^h+}_8-Amr-}_-j/_$(q_4WkS43%4HS7o&/?$
                      ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3309)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2214)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at kotlin.text.Regex.<init>(Regex.kt:89)
        at io.javalin.core.PathParser.<init>(PathParser.kt:27)
        at io.javalin.websocket.WsEntry.<init>(WsPathMatcher.kt:14)
        at io.javalin.websocket.JavalinWsServlet.addHandler(JavalinWsServlet.kt:79)
        at io.javalin.Javalin.addWsHandler(Javalin.java:551)
        at io.javalin.Javalin.ws(Javalin.java:580)
        at io.javalin.Javalin.ws(Javalin.java:569)
        at top.cyqi.websocket.WebSocketServer.start(WebSocketServer.java:98)
        at top.cyqi.GrasscuttersWebDashboard.onEnable(GrasscuttersWebDashboard.java:95)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:131)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:129)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:159)

**Comment by mxtilx** [comment]
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 22
^/Dashboard/DK-.-:25z{G7)[_L9T^h+}_8-Amr-}_-j/_$(q_4WkS43%4HS7o&/?$
                      ^
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.closure(Pattern.java:3309)
        at java.base/java.util.regex.Pattern.sequence(Pattern.java:2214)
        at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at kotlin.text.Regex.<init>(Regex.kt:89)
        at io.javalin.core.PathParser.<init>(PathParser.kt:27)
        at io.javalin.websocket.WsEntry.<init>(WsPathMatcher.kt:14)
        at io.javalin.websocket.JavalinWsServlet.addHandler(JavalinWsServlet.kt:79)
        at io.javalin.Javalin.addWsHandler(Javalin.java:551)
        at io.javalin.Javalin.ws(Javalin.java:580)
        at io.javalin.Javalin.ws(Javalin.java:569)
        at top.cyqi.websocket.WebSocketServer.start(WebSocketServer.java:98)
        at top.cyqi.GrasscuttersWebDashboard.onEnable(GrasscuttersWebDashboard.java:95)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:131)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:129)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:159)
Screenshot_2022-06-19-20-47-25-93

**Comment by GioroGiori** [comment]
Apparently this has problems with 2.8 and it is not possible to use serenitea pot
this is the error log in grasscutter

java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.home.HomeSceneItem.calComfort()" because "homeRoomScene" is null
        at emu.grasscutter.server.packet.send.PacketHomeComfortInfoNotify.<init>(PacketHomeComfortInfoNotify.java:35)
        at emu.grasscutter.game.home.GameHome.onOwnerLogin(GameHome.java:72)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1389)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Pull request merged**
